### ISSUE TITLE
В поле в ремонте на Главной не отображается ничего

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#100]
Должно отображаться Да или Нет, желательно в виде ссылки по нажатию которой открывается интерфейс Ремонт

**Comment by Neolined** [comment]
![Безымянный](https://user-images.githubusercontent.com/80521325/127483469-e5d70d02-177d-4ce0-9572-7b15bfed0183.png)
У меня отображается. Может быть проблема с таблицами?

@adc-san

**Comment by ADC-Andrei** [comment]
У меня тоже не отображается. Ячейки этого столбца пустые.
Пробовал интернет эксплорером, хромом, мозилой.

**Comment by adc-san** [comment]
repair - varchar(100) 
В таблице все ячейки этого столбца пустые(NULL), в таком случае должно отображаться "Нет" на Главной.

**Comment by adc-san** [comment]
При этом, если открыть интерфейс Ремонт, для любого изделия - то там надпись "Изделие уже в ремонте"

**Comment by ADC-Andrei** [comment]
А я тут задался вопросом, а нужен ли нам этот столбец?
Ведь "в ремонте" можно представить себе не как статус или состояние, а как местоположение. Туда и запихать. Меньше столбцов - меньше путаница!

**Comment by adc-san** [comment]
Нет, нельзя.
Местоположение ="ремонт" это значит, что оно лежит на полочке плат для ремонта.
А статус "в ремонте"="Вася", значит что Вся эту плату уже ремонтирует.

**Comment by Neolined** [comment]
Исправлено: 0b387de6c2d280a663e0b76673e46eba14633837

@adc-san
