### ISSUE TITLE
Новый интерфейс "Формирование заказа"

### ISSUE THREAD

**Issue by Neolined** [Neolined/DatabaseADC#101]
Интерфейс для сотрудника, который создает заказ. На сегодняшний день для Андрея Николаевича Верещагина.
а.) Создается поле для ввода номера нового, не существующего в базе, заказа, который автоматически заполняется ближайшим свободным номером, следующим по порядку "кодировки" за крайним заказом, имеющимся в базе.
б.) Создаются два поля для ввода:
1. "Тип изделия" с автозаполнением из `list_of_products`.
2. "Название изделия" с автозаполнением из `list_of_products`.
3. "Количество".
Рядом по нажатию "+", появляется еще окно с вышеуказанными полями.
Внизу кнопка "Сформировать заказ".

@ADC-Andrei
@adc-san
@alx4

**Comment by Neolined** [comment]
Коммит: 3ea5be6d7aa35db89aa8d44395646fe0a747354e
Есть возможность создавать заказы. Пока нет возможности их редактировать с точки зрения БД - работаю над этим, а веб-интерфейс продуман для редактирования.
Для работы с веб-интерфейсом, необходимо привести таблицы в БД к следующему виду: https://github.com/Neolined/DatabaseADC/issues/112#issuecomment-916694903

@adc-san
@alx4

**Comment by adc-san** [comment]
Перенёс в https://trac.adc-line.ru/mc-04/ticket/874
