### ISSUE TITLE
Новый интерфейс "Комплектование заказа"

### ISSUE THREAD

**Issue by Neolined** [Neolined/DatabaseADC#102]
Интерфейс для сотрудника, который присваивает платам серийные номера. На данный момент это В. Ольга Марсельевна.
а) Появляется поле для ввода номера заказа и кнопка "Отправить".
б) По нажатию открывается следующий интерфейс:
Списком поля таблицы, как на главной странице: "id" - просто перечисление без привязки к базе; "Тип"; "Имя"; поле ввода для серийного номера. Справа кнопка сохранить. 
1. После нажатия => Если существует серийный номер в `products`: 
Если владелец не 'АДС', то выдать ошибку, если нет, то записать в таблицу `orders` => `serial`. 
2. После нажатия =>Если не существует платы в базе:
Записать в `products` => `serial`, `type` = тип , `name` = имя, `location` = 'work', `owner` = 'АДС', `date` = now(), `testing` = 'notest'???, `otk` = 'nocheck', `mismatch` = 'no', `repair` = 'no', `comment` = 'no'.
Записать в `history` => `uid` (из `products`), `type_write` = 'record', `worker`, `date` = now(), `order_from` = 'stock(склад)', `whom_order` = `work(производство)`, `comment` = 'product from stock, add in list of 'ship(продукт со склада, добавлен в лист отправки). Жду комментариев.

**Comment by adc-san** [comment]
Перенёс в https://trac.adc-line.ru/mc-04/ticket/874
