### ISSUE TITLE
Улучшение: отвязать автодополнение от начала строки

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#104]
Сейчас при вводе текста в текстовые поля, имеющие функцию автодополнения (см. #61), пользователю выдаются подсказки, состоящие из уже имеющихся в базе значений, **начало** которых совпадает с введенным текстом.  Однако в случаях, когда пользователь начинает ввод значения не с начала, функция автодополнения не работает (не опознает введенный текст как часть уже имеющегося значения). Например, пользователь вводит в поле "владелец" строку "Роснефть", он не получает подсказку о том, что в базе данных уже имеется значение "АО Роснефть". Как результат, сохраняется вероятность занести в базу данных два разных наименования одной и той же компании.

Предлагаю при вводе значения в текстовое поле выдавать в качестве подсказки не только значения, начинающиеся с введенного текста, но и значения, **содержащие** введенный текст в любом месте.

**Comment by ADC-Andrei** [comment]
+1

**Comment by adc-san** [comment]
Перенёс сюда: https://trac.adc-line.ru/mc-04/ticket/876#ticket
