### ISSUE TITLE
Стандартные сценарии работы в браузере.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#105]
Я заметил что в интерфейсах базы не работают корректно привычные сценарии работы в браузере.
Например, когда я нажимаю Ctrl+клик на одной из ссылок на главной я ожидаю, что ссылка откроется в новой вкладке, а я останусь в текущей вкладке на Главной, вместо этого при нажатии Ctrl+клик в текущей вкладке открывается ссылка, а в новой вкладке открывается главная страница.

Предлагаю во всех местах где это возможно использовать "нормальные ссылки" чтобы пользователь мог работать с ними, как он привык.

**Comment by ADC-Andrei** [comment]
Ctrl+клик = клик колесом мыши. У меня работает правильно в хроме, мозиле и вивальди

**Comment by ADC-Andrei** [comment]
Как оказалось, у меня правильно работают ссылки только в меню. Ссылки в ячейках главной, действительно, работают неадекватно.
