### ISSUE TITLE
Добавить кнопку "применить" к фильтрам главной страницы

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#106]
Давно хотел предложить добавить кнопку "применить", так как без нее почти невозможно догадаться, как применить установленный мной фильтр. Например вводу в поле "Дата" даты "от" и "до", и что я после этого должен сделать, чтобы в таблице отображались только записи, попадающие в диапазон между "от" и "до"? Непонятно...
![ss1](https://user-images.githubusercontent.com/84128875/128465560-85864082-5235-477b-8201-8232f0abee61.jpg)

**Comment by adc-san** [comment]
Так есть же кнопка Применить...
![image](https://user-images.githubusercontent.com/36914827/128499020-633621c0-b8b5-418c-b091-094aabb3f3f0.png)

**Comment by alx4** [comment]
> Так есть же кнопка Применить...

О, спасибо! Не заметил ее.

**Comment by alx4** [comment]
> Так есть же кнопка Применить...

Может быть ты еще случайно знаешь, для чего служит кнопка "Очистить"?

**Comment by adc-san** [comment]
Да знаю, она для того чтобы сбросить все фильтры в дефолтное значение(но не применяя их в отличии от кнопки Сбросить). мне эта кнопка кажется избыточной, я её, например не пользуюсь, подумывал предложить убрать её для упрощения...
