### ISSUE TITLE
Добавить поле ввода наименования в фильтры

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#107]
Сейчас чтобы в фильтрах на главной странице задать поиск только одного конкретного типа платы надо найти этот тип в длинном списке (прокручивая его в довольно маленьком окне) и отметить чекбокс. Это долго и неудобно.

Думаю, в подавляющем большинстве случаев пользователя будет интересовать один конретный тип платы, и его гораздо проще и быстрее ввести как текст. Предлагаю дополнить фильтр полем ввода, в котором можно было бы просто текстом набрать наименование платы (с автоматической подсказкой вариантов). При необходимости найти несколько типов плат их можно вводить через запятую (см. как пример ввод в поле "Копия" при создании тикетов в trac). Список изделий с чекбоксами можно оставить как альтернативный вариант, хотя лично мое мнение - вряд ли кто-то будет им пользоваться при наличии строки ввода.
![ss1](https://user-images.githubusercontent.com/84128875/128466648-7e97f254-e983-4604-b519-03417945bf7c.jpg)

**Comment by adc-san** [comment]
Не по теме тикета. но за одно: я вижу на твоём скриншоте, что фильтры выглядят у тебя "некрасиво", не так как задумывал автор.
Вот смотри как должно быть:
![image](https://user-images.githubusercontent.com/36914827/128498283-356e8686-cf3d-4ba9-a6aa-635908d2f956.png)
Думаю стоит написать об этом отдельно.

По теме тикета, да строка ввода может быть полезна, но и выбор чекбоксами нельзя убирать: некоторые люди предпочитают выбрать из нарисованного списка нежели вводить руками

**Comment by alx4** [comment]
> Вот смотри как должно быть:

Так это ты не мне показывай, как должно быть, а автору, который в 97b0602d2c1de5750bf7a6db76c68b67d4263b5a установил всем чекбоксам `width: -moz-available`.

:)

**Comment by ADC-Andrei** [comment]
Это опять Мозила отображает не так)))

**Comment by alx4** [comment]
> Это опять Мозила отображает не так)))

А что здесь не так? Автор установил чекбоксу ширину -moz-available, и Мозилла заняла им всю ширину столбца:
![ss1](https://user-images.githubusercontent.com/84128875/128502560-93b89d13-650f-4ec2-a6ed-c0f7b6c0c9b5.jpg)

По-моему, что просили, то и получили...

**Comment by alx4** [comment]
Открыл в Хроме и установил инпутам `width: -webkit-fill-available` (гугловский аналог мизолловского `width: -moz-available`) - и получил то же самое:
![ss2](https://user-images.githubusercontent.com/84128875/128503415-46ca83ca-7296-4837-a38f-f5eb4eced17b.jpg)

**Comment by adc-san** [comment]
Перенёс сюда: https://trac.adc-line.ru/mc-04/ticket/877#ticket
