### ISSUE TITLE
Удалить из базы данных и веб-интерфейса в поле perfomance

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#108]
В таблице products имеется столбец "perfomance", имеющий тип varchar(100). В веб-интерфейсе на главной странице этот столбец озаглавлен как "Исп." (ранее там было "Исполнение"). Однако, насколько я могу видеть, в базе данных туда записаны вовсе не номера исполнений изделий, а что-то мне непонятное - "3U", "без SFP", "v4" и т.п. - похоже просто на какие-то комментарии...

Предполагаю, что, судя по заголовку столбца, в этом поле все-таки должен содержаться номер исполнения изделия, и, если это действительно так, то имеет место баг.

Как стало ясно из [комментария](https://github.com/Neolined/DatabaseADC/issues/108#issuecomment-894168095) @adc-san, поле perfomance в таблице products более не нужно. **Предлагаю** удалить это поле из таблицы и веб-интерфейса.

**Comment by adc-san** [comment]
Для номенклатуры изделий в базе с некоторых пор есть договорённость, что каждое исполнение платы заведено в базу как отдельный тип изделия, приведу пример платы S-port, у неё по КД есть три исполнения с номерами 3, 5 и 12.
В номенклатуре базы заведены 4 типа изделия: S-port (просто доска и плата неопределённого исполнения. когда часть элементов ещё не запаяна, полуфабрикат короче), S-port-3, S-port-5, S-port-12
При таком подходе столбец Исп. просто не нужен и его можно удалить.

**Comment by alx4** [comment]
>       При таком подходе столбец Исп. просто не нужен и его можно удалить.

Понял. Скорректировал предложение тикета.

**Comment by Neolined** [comment]
Готово: 1aa0172e06f34160fe57fa49ef9eca9a3c31bde0

@adc-san
@alx4
@ADC-Andrei

**Comment by ADC-Andrei** [comment]
Делай Close если готово))

**Comment by alx4** [comment]
> Делай Close если готово))

Готово-то еще не совсем. :) @Neolined только убрал использование этого поля из веб-интерфейса, то есть выполнена только вторая часть предложенного улучшения. В таблице поле по-прежнему есть. Прежде чем его удалить, надо сначала обновить веб-интерфейс на сервере. Вот когда веб-интерфейс будет обновлен, а столбец perfomance удален из базы, мое предложение будет полностью реализовано. :)

**Comment by alx4** [comment]
@adc-san, а почему ты закрыл тикет несмотря на то, что улучшение выполнено лишь частично? Ты предполагаешь для каких-то целей оставить в таблице products поле performance?

**Comment by adc-san** [comment]
Нет, я его удалил. теперь всё полностью выполнено.

**Comment by alx4** [comment]
> Нет, я его удалил. теперь всё полностью выполнено.

Теперь - да, но когда я писал вопрос, поле еще было. :)

**Comment by alx4** [comment]
> Для номенклатуры изделий в базе с некоторых пор есть договорённость, что каждое исполнение платы заведено в базу как отдельный тип изделия, приведу пример платы S-port, у неё по КД есть три исполнения с номерами 3, 5 и 12. В номенклатуре базы заведены 4 типа изделия:
> * S-port (просто доска и плата неопределённого исполнения. когда часть элементов ещё не запаяна, полуфабрикат короче)

Хм... А для чего в номенклатуру изделий занесено то, что изделием не является (полуфабрикат)?

>   При таком подходе столбец Исп. просто не нужен и его можно удалить.

Хорошо. Есть, например, в БД изделие (плата) с серийным номером E02528. Как узнать номер исполнения этой платы (я его знаю, интересен именно предлагаемый порядок действий)?
