### ISSUE TITLE
-moz и -webkit

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#109]
В  разговорах #107, #90 выяснилось, что в некоторых случаях используются специфичные значения css свойств например `width: -moz-available`, которые понятны не всем браузерам. Это приводит к значительным различиям внешнего вида интерфейса в разных браузерах.
Думаю что в дебри проприетарных и экспериментальных фич браузеров нам лезть не стоит, да и необходимости скорее всего нет, у нас интерфейс довольно простой и строгих требований к его рисованию нет, считаю что можно обойтись стандартными средствами.

**Comment by alx4** [comment]
Как формалист и буквоед со стажем :) замечу, что @adc-san отметил тикет как enhancement, однако в комментарии ничего не предложил, а только выразил мнение. :)

От себя же добавлю, что лично я ничего не имею против использования нестандартных стилей, если они являются **дополнениями** к стандартным. Однако пока я наблюдаю другую картину. Вот первый же попавшийся пример:
https://github.com/Neolined/DatabaseADC/blob/390a2b793c7a287b28f4c6cdec4d332f781db34c/css/main.css#L15-L17

Здесь для своего "любимого" браузера автор установил выравнивание текста по центру какого-то элемента, а для других браузеров оставил выравнивание влево...

**Comment by adc-san** [comment]
> ничего не предложил

А, ну да :) - предлагаю обойтись стандартными средствами.

**Comment by adc-san** [comment]
https://trac.adc-line.ru/mc-04/ticket/869#ticket
