### ISSUE TITLE
Интерфейс заказы.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#112]
Требуется изменить интерфейс Заказы.
1. Отображать заказы в таблице так - номер заказа / дата создания/ срок исполнения(дата)/ статус/ получатель
2. Статус: принят, скомплектован, проверен, прошёл ОТК, отгружен.
- Принят - устанавливается работником производства(начальником) со специальным правом "get_order" через интерфейс "Наполнение заказа" - подтверждается получение заказа производством.
- Скомплектован - устанавливается автоматически через интерфейс "Комплектование заказа" когда ко всем изделиям в заказе добавлены конкретные серийные номера.
- Проверен -  устанавливается автоматически через интерфейс Тестирование
- Прошел ОТК -  устанавливается автоматически через интерфейс ОТК
- Отгружен - устанавливается через интерфейс отгрузка
3. Фильтр по статусам
В таблицу orders нужно добавить соответствующие поля.

Также см. #101, #102, #78

**Comment by ADC-Andrei** [comment]
> 1. Отображать заказы в таблице так - номер заказа / дата создания/ статус/ получатель

Предлагаю еще добавить дату, к которой заказ должен быть завершен.
> 2. Статус: принят, скомплектован, проверен, прошёл ОТК, отгружен.
> 
> * Принят - устанавливается работником производства через интерфейс "Наполнение заказа" - подтверждается получение заказа производством.

Наверно не любым работником, а тем, кто в данный момент руководит отделом? Иначе какой-нибудь работник примет, а начальник в новых заказах ничего не найдет.
> * Скомплектован - устанавливается автоматически через интерфейс "Наполнение заказа" если заказ "наполнен".

Так, может, интерфейс так и назвать "Комплектование заказа"? Статус TRUE когда все позиции для заказа зарезервированы - вынесены со склада, помещены на отдельную полку, к изделиям в "Заказах" добавлены конкретные номера.
> * Проверен -  устанавливается автоматически через интерфейс Тестирование

Когда ВСЕ изделия заказа будут протестированы успешно. Тогда автоматически можно добавить статус "В проверке" - когда успешно проверено изделий больше НОЛЬ, но меньше ВСЕ.
> * Прошел ОТК -  устанавливается автоматически через интерфейс ОТК

Может быть имелось в виду не "через интерфейс ОТК", а "при успешном ОТКировании всех изделий заказа" ?
> * Отгружен - устанавливается через интерфейс отгрузка
> 
> 1. Фильтр по статусам
>    В таблицу orders нужно добавить соответствующие поля.
> 
> Также см. #101, #102, #78

Я немного запутался в терминологии. Если статус устанавливается "автоматически", то интерфейс упоминать наверно не нужно? А если статус нужно менять в каком-то интерфейсе, то это уже ручное изменение, а не автоматическое.

**Comment by adc-san** [comment]
"Автоматически через интерфейс", значит что при запуске пользователем интерфейса скрипт должен проверить условия и изменить статус. Например, ты сделал ОТК последней платы в заказе - после нажатия кнопки отправить запустился скрипт интерфейса ОТК, данные были внесены в базу затем выполняется проверка все ли платы заказа прошли ОТК успешно и если да, то заказу устанавливается статус = Прошел ОТК.

Предложения внёс в тикет.

**Comment by Neolined** [comment]
Выполнение.
1. Создание таблицы orders:
create table `orders1` (id integer not null,
    `date` date not null,
    `deadline` date not null,
    `status` enum ('accept', 'completed', 'verify', 'otk', 'shipped'),
    `recipient` varchar (200) not null)
2. Создание таблицы orders-items:
CREATE TABLE `order-items` (
    order_id INT(32) NOT NULL,
    serial VARCHAR(100),
    type VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    parent VARCHAR(100),
    UNIQUE KEY (order_id,serial),
    FOREIGN KEY (order_id) REFERENCES orders (uid) ON DELETE CASCADE,
    FOREIGN KEY (serial) REFERENCES products (serial) ON DELETE RESTRICT)

@adc-san

**Comment by alx4** [comment]
>        CREATE TABLE `order-items` ( //  order-items - в кавычках, наклонённых влево, иначе при создании будет ошибка
...
>        UNIQUE KEY (order_id,serial),

Я правильно понял, что одно и то же изделие может присутствовать в нескольких разных заказах?

**Comment by adc-san** [comment]
Да, правильно.

**Comment by adc-san** [comment]
Перенёс в https://trac.adc-line.ru/mc-04/ticket/874
