### ISSUE TITLE
Улучшение: отображать и имя, и логин сотрудника, ответственного за ремонт

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#114]
Комментарий к коммиту f3490362f703fad7b4e3877c622a21fa8a6b1b70 навел меня на мысль о том, что при указании пользователя, ответственного за ремонт изделия, было бы полезно отображать и реальное имя, и логин. Реальное имя дает удобство (не обязательно помнить логин каждого сотрудника), а логин дает уникальность в случае, если есть несколько сотрудников с одним и тем же именем. Для экономии места логин можно поместить в title элемента, чтобы он отображался при наведении курсора на имя. Прошу считать это предложением по улучшению.

**Comment by Neolined** [comment]
Улучшено в: 405364f3d97b942c6aa52a8903da388bfd521c10

@alx4
