### ISSUE TITLE
Улучшение: в интерфейсе Возврат отображать текущего Владельца и  Местоположение изделия

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#116]
Работники производства говорят что так будет значительно удобнее, если сразу можно увидеть где была плата до возврата и убедиться что всё правильно
Предлагаю выводить эту информацию рядом с именем:
Плата SW-01 (Склад)
Плата PS-48 (ООО Ростелеком)

**Comment by ADC-Andrei** [comment]
В предложенном примере местоположение или владелец?

**Comment by adc-san** [comment]
И то и другое. Если владельца нет(подразумевается АДС), то вывести только Местоположение, и если местоположения нет, то вывести только владельца), если и то и другое есть, то будет:
PS-220D-12 (Ремонт, АО Уралгазнефть)

**Comment by adc-san** [comment]
перенёс тикет в trac
