### ISSUE TITLE
Неверное отображение имени пользователя

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#117]
Ранее в базе данных пользователь имел имя (`users.worker`) "Ronnie O'Sullivan".
После аутентификации пользователя в веб-интерфейсе имя пользователя было изменено на "Alex Mogilnikov".
**После изменения имени** в базе пользователь создал запись платы (через интерфейс "Возврат") и принял плату в ремонт (через интерфейс "Ремонт"). В результате в веб-интерфейсе отображается вперемешку как старое, так и новое имя, хотя я ожидал, что имя везде будет отображаться новое:
![ss1](https://user-images.githubusercontent.com/84128875/135625382-5c4ce99d-66a5-4a7c-8155-11d1c720a44d.jpg)

**Comment by adc-san** [comment]
Алексей, я переношу этот проект в траку: [тикеты тут](https://trac.adc-line.ru/mc-04/query?status=!closed&component=%D0%91%D0%94+%D0%B8%D0%B7%D0%B4%D0%B5%D0%BB%D0%B8%D0%B9+%D0%90%D0%94%D0%A1) а [код тут](https://trac.adc-line.ru/mc-04/browser/base).

Этот тикет тоже перенёс: https://trac.adc-line.ru/mc-04/ticket/875
