### ISSUE TITLE
Интерфейс ремонт

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#17]
Поле ввода серийного номера + кнопка
По кнопке :
- вывод типа и имени изделия  + вывод статуса ремонта: "Не в ремонте" или В ремонте: <ФИО ремонтирующего>
- Если "Не в ремонте" то вывести кнопку Принять в ремонт (
- Если "в ремонте":
  - появляется текстовое поле ввода "Диагностика" и кнопка "Записать диагностику" (работает аналогично полю и кнопке Несоответствия в #16)
  - появляется текстовое поле ввода "Ремонт" и кнопка "Записать ремонт"  (При нажатии вносится только запись в историю с типом repair)
  - появляется кнопка "Закончить ремонт" выбор "Отремонтировано" / "Не отремонтировано" (при нажатии запись в продукты repair=null, запись repair в историю со статусом yes, и если отремонтировано, то запись в продукты mismatch=yes)

**Comment by Neolined** [comment]
Исправил: 4c41161b9629c69884b48825febe222afd0140c1
При записи диагностики и ремонта, раскрывается интерфейс и отображается введённый серийный номер. Также отображается номер при принятии в ремонт и записывается в таблицу история запись о принятии в ремонт.

@adc-san
