### ISSUE TITLE
Андрей предлагает новую опцию для отображения на главной странице.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#31]
Галочку, при нажатии которой, отфильтрованные и отсортированые изделия показываются не все а в штуках по имени.
Примерно как в Отгрузке.
Это бы позволило легко посмотреть, например, сколько плат SM-01 имеют не соответствия, и другие полезные данные не залезая в вывод каждой платы.

**Comment by Neolined** [comment]
Реализовано: 3b942283c0b74ca6702fd5d1933fc04471853b05
Теперь можно указать в фильтрах - "Отобразить количественно" и выводится будет количество тех или иных изделий, сгруппированных по совпадающим имени и типу

**Comment by ADC-Andrei** [comment]
Давай обзовем "Отобразить количество", а то какие-то сложные обороты...

**Comment by Neolined** [comment]
Сделано: 164f946e07a707a6801f7511434c695fb8275a74
@adc-san
