### ISSUE TITLE
Несоответствия. ошибка при попытке записи

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#32]
Проверяю в  https://github.com/Neolined/DatabaseADC/commit/3b942283c0b74ca6702fd5d1933fc04471853b05
При попытке записи - ошибка:
> Error recording in table history:Incorrect integer value: '' for column `adcproducts`.`history`.`UID` at row 1

Странно потому что я делал записи несоответствий и проблем не было. Видимо от чего-то зависит проявление бага.

**Comment by Neolined** [comment]
Исправлено: 75e51df57283095482c28cdeb7b25756fc23b1e4
