### ISSUE TITLE
Несоответствие полей текста и длины строк в базе

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#34]
В Некоторые текстовые поля можно вводить текст длиной больше чем ограничение в базе, при попытке записи возникает ошибка в базе, Например  в отгрузке можно получить:
> Ошибка записи в таблицу "История":Data too long for column 'whom_order' at row 1

**Comment by Neolined** [comment]
Исправил: 101fd4034e39ad38cbc82c32c3da9fc66a97ee50

**Comment by adc-san** [comment]
Остались:
Отгрузка -> получатель
Возврат -> От кого

**Comment by Neolined** [comment]
Исправил: dcb6c2bef166d349bccf7bb96c89028b5ef48bd9
