### ISSUE TITLE
Сломались права

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#38]
Зарегистрировался новым пользователем. Прав у него соответственно нет (пустая строка в root).
Однако ему доступен интерфейс Приёмка , Главная и Заказа
Пользователю с root="test" также доступна приёмка.
Если у пользователя root=пусто, то он не должен видеть ничего, даже главную и заказы, это пока чужой для нас, не одобренный админом.
Если у него в root есть любой текст, то Главную и заказы он может видеть.

**Comment by adc-san** [comment]
Тестировал в https://github.com/Neolined/DatabaseADC/commit/7d4a6f9f134015062b389075d07fd2ea6a5ae894

**Comment by adc-san** [comment]
уточнил ошибку

**Comment by Neolined** [comment]
Исправлено: 62128e722a776e024b478871c43da6f2e2f89ac2
@adc-san
