### ISSUE TITLE
Сломалась сортировка

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#39]
Выбираю в разных столбцах прямая / обратная сортировка, нажимаю Применить фильтры и страничка никак не меняется.
https://github.com/Neolined/DatabaseADC/commit/7d4a6f9f134015062b389075d07fd2ea6a5ae894

**Comment by adc-san** [comment]
Сортировка не работает когда в фильтрах ничего не выбрано.
Если выбрать что-то в фильтрах, сортировка начинает работать.

**Comment by Neolined** [comment]
Исправлено в #41
