### ISSUE TITLE
Автоматические подсказки не дают выбрать правильное значение.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#40]
Ввожу первые буквы платы - появляются варианты, выбираю нужный мышью, а в результате выбирается какой-то другой.
Тестил в Приёмке в полях Тип  и Имя.
https://github.com/Neolined/DatabaseADC/commit/7d4a6f9f134015062b389075d07fd2ea6a5ae894

**Comment by Neolined** [comment]
Исправлено: d319d2075bdd7ba07dd4eac6f2fc1d700cac3640
Саш, не забудь на странице нажать Ctrl + F5, чтобы обновить JavaScript

@adc-san

**Comment by adc-san** [comment]
Пользователи хотят иметь возможность выбирать вариант не только мышью а ещё и клавиатурой(стрелками + Enter) есть такая возможность?

**Comment by Neolined** [comment]
Исправлено: 7da5c36584c2b75ccf529408d644fd4af374fdf2
Теперь есть возможность выбирать вариант не только мышью а ещё и клавиатурой(стрелками + Enter)
