### ISSUE TITLE
Слишком строгие требования к логину

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#42]
Предлагаю разрешить в логине, как минимум, латинские заглавные, ну и можно дать больше спецсимволов, хотябы те что есть на клавиатуре

**Comment by Neolined** [comment]
Улучшено: 1deb4ff01a591579c6d68601553fbb6ec7143d7c
Разрешены в логине латинские заглавные и большая часть спецсимволов с клавиатуры

@adc-san
