### ISSUE TITLE
Не снимается фильтр "показать количество"

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#43]
Ставлю в фильтрах SW-01 + количество, применяю - фильтрует SW-01 указывая количество
Затем снимаю фильтр количество, делаю применить и вижу что фильтр количество не снят.

**Comment by adc-san** [comment]
баг проявляется только в паре с другим фильтром, если только показать количество ставить - то всё ок

**Comment by Neolined** [comment]
Исправлено в: 8c6216db038dfb3ff5e27d7d759921057e3bdefa

@adc-san
