### ISSUE TITLE
Дополнительные функции интерфейса Возврат

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#44]
После поля "От кого" нужно добавить выпадающий список "Куда" c вариантами: Склад, Разработка, Изолятор брака, Неликвид
Пользователь должен обязательно выбрать.
При записи выбор пользователя запишется в products->location
Набор значений поля расширил: location enum('stock','shipped','develop','isolator','nelikvid') и внёс в #12

**Comment by Neolined** [comment]
Исправлено: 20eb89095154ca7c1589afe9c793ebb464c8a8ee
Добавил выпадающий список "Куда" c вариантами: Склад, Разработка, Изолятор брака, Неликвид

@adc-san

**Comment by adc-san** [comment]
Внимание
