### ISSUE TITLE
Добавить ещё один формат серийного номера

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#45]
Оказалось, что кроме основного формата серийников есть ещё один, нужно добавить его поддержку в Приёмку.
1 Русская заглавная + 4 цифры
Например Б1234

**Comment by Neolined** [comment]
Улучшено: 4a92759c57ae54c40180469b745e0f5a7f3b28da

@adc-san

**Comment by adc-san** [comment]
Добавлю сюда
И я нашёл ещё один формат серийника :)
Просто пять цифр, например 12345.
Нужно добавить и этот формат.

**Comment by adc-san** [comment]
В "возврате" ещё  проверяется формат номера, в какойто мере, а возможно и в других интерфейсах.
Я думаю. что везде кроме приёмки проверку на формат серийника можно убрать, т.к. там на чтение запрос и только в приёмке на запись

**Comment by Neolined** [comment]
В "возврате" тоже происходить запись в БД. #21 

@adc-san

**Comment by adc-san** [comment]
Да ты прав.
Значит нужно так и проверять, как есть, в возврате и приёмке. Просто добавить ещё один шаблон номера.

**Comment by Neolined** [comment]
Сделано: e911551ca3ab193b67c55d8f73a5d173cbea28ef

@adc-san
