### ISSUE TITLE
Удалить Вхождение и Програмное обеспечение

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#46]
Предлагаю пока удалить из БД колонки Вхождение и Программное обеспечение.
Я удалю колонки из БД нужно проверить, что ничего не поломается в софте.

**Comment by Neolined** [comment]
Улучшено: cb053d197b2ffa99a6e435f9fec3f1f7ebad80ba
Удалил колонки Вхождение и ПО в локальной БД. Произвел изменения, чтобы ничего не сломалось при работе веб-интерфейса

@adc-san
