### ISSUE TITLE
Ошибки в Title

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#47]
В отгрузке Title ошибочно указан как Интерфейс испытателя
В ремонте - интерфейс приёмщика

**Comment by Neolined** [comment]
Исправлено: 2a5e1e3de10e44f47e143a9c45cc8de2e2f9a73e


@adc-san

**Comment by adc-san** [comment]
В ремонте - интерфейс приёмщика

**Comment by Neolined** [comment]
Исправил : 547b94c4f41d02bb830157650d1ea334c401d542
