### ISSUE TITLE
Новые значения location

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#48]
1. На Главной нужно перевести на русский новые значения location 
location enum('stock','shipped','develop','isolator','nelikvid','repair','work')
Склад, Отгружено, Разработка, Изолятор брака, Неликвид, Ремонт, Производство.

2. В выпадающий список  в интерфейсе Возврат-  добавить новые варианты "В ремонт" и "Производство".

**Comment by adc-san** [comment]
И ещё появилась новая локация work
location enum('stock','shipped','develop','isolator','nelikvid','repair','work')

Добавлю в основное сообщение все новые локации

**Comment by Neolined** [comment]
Улучшено: ee4bac903aea18d3b2d51a28775fca6947b0b173
1. Перевел на русский новые значения location на "Главной"
2. В выпадающий список в интерфейсе "Возврат" добавил новые варианты "В ремонт" и "Производство".

@adc-san
