### ISSUE TITLE
Новый Интерфейс "Номенклатура"

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#49]
Отдельных прав доступа нет, права проверяются как на главной.
Вывести на страничку интерфейса всё из list_of_products с разбивкой по type
Вывести с сортировкой по type в алфавитном и с сортировкой внутри type по name в алфавитном.

Выглядеть должно примерно так:

Модуль:
  DSL
  DSL.BisM
  E1-3U
  
Плата:
  SM-01
  SW-01
  
  .....

**Comment by Neolined** [comment]
Сделано: 3111e8ab3bbd1ab5bd88925be53d217a54f22be2

@adc-san
