### ISSUE TITLE
Нужно поставить таймаут жизни куков побольше

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#50]
Сейчас слишком быстро теряется авторизация, за час кажется...
Нужно часов 12 или 24

**Comment by Neolined** [comment]
Читаю и не могу понять в чем дело. У меня сессия 24 минуты, но работает она дольше. В интернете пишут, что зависит все от очищения кэша какого-то, так и не могу разобраться. Предлагаю так. Я могу написать на каждой странице "ini_set('session.gc_maxlifetime', 86400);" перед session_start, либо ты можешь в конфигурационном файле php.ini указать время сессии "session.gc_maxlifetime = 86400". Как лучше? У меня почему-то на различные изменения не реагирует браузер

@adc-san

**Comment by adc-san** [comment]
Хм.. Давай пока отложим этот вопрос
Я тут немного почитал почитал, и слишком там всё интересно) Если мы установим своё время жизни сессий для сборщика мусора, то т.к. сессии и наши и других приложений на сервере по умолчанию хранятся в одной папке, то чужой сборщик мусора всё-равно может их удалить :( https://web.archive.org/web/20130303043400/https://www.leftontheweb.com/message/php-session-expiry 
https://stackoverflow.com/questions/520237/how-do-i-expire-a-php-session-after-30-minutes
https://stackoverflow.com/questions/156712/what-is-the-default-lifetime-of-a-session
Пока я просто добавил в свой .htaccess строчку `php_value session.gc_maxlifetime "86400"` посмотрим что выйдет.

**Comment by adc-san** [comment]
Засунул в  .htaccess  такие настройки:

php_value session.gc_maxlifetime "86400" //24 часа
php_value session.gc_divisor "1"     
php_value session.gc_probability "1"  //Вместе с предыдущей настройкой задаёт вероятность запуска сборщика мусора=1
php_value session.cookie_lifetime "0"  //куки валидны до закрытия браузера
php_value session.save_path "/var/www/html/base/SessionData"  //отдельный каталог для хранения "наших" сессий

Посмотрю как это теперь будет работать, пока 40 минут уже моя сессия прожила...

**Comment by adc-san** [comment]
Да, всё отлично. Сессия живёт и через сутки бездействия умирает. Оставлю так.
