### ISSUE TITLE
Новый фильтр Склад

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#51]
Предыстория. Со вчерашнего дня БД начала жить настоящей жизнью с настоящими платами. Практический опыт использования родил некоторые новые заявки на улучшения:

1. Передвинуть набор фильтров "Отображение" влево, пусть это будет первый из фильтров
2. Фильтр "Отобразить количество' переназвать в "Количество" для краткости.
3. В набор фильтров  "Отображение" добавить фильтр "Склад"- можно выбрать только один, либо Количество либо Склад.
"Склад" работает примерно как "Количество" но выводит не общее количество отфильтрованных изделий ,  а  разбивает их отдельно по столбцам в зависимости от location :
![Безымянный](https://user-images.githubusercontent.com/36914827/118811104-0ad99880-b8c6-11eb-9170-bcba5f9ff590.png)
Вывести нужно как в примере на картинке
Только для локаций Склад и Разработка, если среди изделий есть mismatch=yes. то нужно вывести два числа = "общее количество"("количество исправных"). если  неисправных нет. то выводим одно число. Для локаций неликвид, изолятор, производство всегда выводим только общее количество в локациях.

По идее при включении фильтра Склад, остальные фильтры, кроме Тип+имя становятся бессмысленными, наверное можно при установке Склад сбрасывать все фильтры кроме имя и Тип. Но это не обязательно, можно оставить фильтры, положившись на разумность пользователя.

**Comment by alx4** [comment]
> Со вчерашнего дня БД начала жить настоящей жизнью с настоящими платами

IMHO рановато, не готова она еще к этому - см. например #55. По крайней мере стоит иметь в виду, что сейчас содержимому БД доверять нельзя...

**Comment by adc-san** [comment]
Пока данных не так много, контролирую их вручную периодически.

**Comment by adc-san** [comment]
И я так понимаю что инъекцию может осуществить только зарегистрированный пользователь с каким-нибудь правом (в начале скриптов выполняется проверка checkRoot() и если прав нет, то запросы не будут выполнены)

После регистрации пользователь создаётся без прав, права ему затем вручную назначает администратор(я), так что вроде бы можно не переживать по поводу вторжения чужих в базу :)

**Comment by Neolined** [comment]
Добавлен фильтр "Склад": 2ca35d4d3346a8695e6abe6bab68a719d60332f6

**Comment by Neolined** [comment]
Насчет защиты от Инъекций, я подумывал проверять вводимое пользователем на наличие определенных команд

**Comment by adc-san** [comment]
> Насчет защиты от Инъекций, я подумывал проверять вводимое пользователем на наличие определенных команд

В #55 Алексей предложил использовать mysqli_real_escape_string()

**Comment by adc-san** [comment]
Фильтр работает, но есть небольшая ошибка
в скобочках нужно показывать количество ИСПРАВНЫХ плат в локации, т.е. = количество плат в локации у которых mistmach != 'yes'.

**Comment by alx4** [comment]
Извините что так поздно высказываюсь. Насколько я понял, **фильтр** в разделе "Отображение", о котором идет речь в данном тикете - это вид представления данных, полученных определенным запросом SQL.

Если я понял правильно, то такой подход ("забитые гвоздями" в коде запросы) мне кажется не очень хорошим (очень негибким). Каждый раз, когда кому-то понадобится новый запрос, будет требоваться модификация кода на сервере. Не лучше ли вместо этого дать возможность пользователям самим (через веб-интерфейс) настраивать такие запросы, какие им требуются, сохранять их и затем отображать в разделе "Отображение"? Тогда каждый сможет настроить для себя такие запросы (и, соответсвенно, формы представления данных), какие ему надо, без обращения к разработчику и ожидания доработки кода...

В качестве примера подобного подхода смотрите, как это сделано в [trac](https://trac.edgewall.org/) (функция редактирования отчетов).

**Comment by Neolined** [comment]
Исправлено: a7a7e7f986e946bff3f7d19b4d9cdd331d54e869
Скобочках показывается количество ИСПРАВНЫХ плат в локации, т.е. = количество плат в локации у которых mistmach != 'yes'.

@adc-san

**Comment by adc-san** [comment]
> Если я понял правильно, то такой подход ("забитые гвоздями" в коде запросы)
Ты правильно понял. 
Но я пока не вижу большой необходимости делать лишнюю работу для реализации сложных запросов(согласен что это было бы лучше и гибче). Я думаю что пары забитых гвоздями шаблонов хватит для специфических потребностей. А всё остальное наборами фильтров можно добыть из базы.


> Исправлено
Денис, теперь другая ошибка, теперь число в скобочках отображается всегда если не ноль, а должно отображаться **только если** количество плат в локации и количество исправных **не совпадают**. Т.е. если неисправных плат в локации нет, то нужно выводить только одно число, без скобочек.

**Comment by Neolined** [comment]
Исправлено: 16d900ebeaba775e8d952d870633186c27b4e1ca
Теперь число в скобочках отображается только если количество плат в локации и количество исправных не совпадают
