### ISSUE TITLE
Отображать тип и имя изделия в интерфейсах  Возврат и Несоответствие

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#53]
В интерфейсе Возврат и в интерфейсе Несоответствие при вводе серийника который есть в БД нужно отобразить Тип и Имя изделия, для самоконтроля.

В виде:  Плата FS-08

**Comment by Neolined** [comment]
Добавлено в: 4a58d08935f50fb3b42e8a0507695c8ba7657528

@adc-san
