### ISSUE TITLE
Отображать меню в соответствии с правами пользователя.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#54]
Есть предложение отображать только те пункты меню на которые у пользователя есть права доступа.
Зачем ему видеть остальные? На мой взгляд это повысит удобство использования системы.
Но это красивости, приоритет улучшения низкий, можно сделать когда более критичные вопросы будут решены.

**Comment by Neolined** [comment]
Улучшено в: c8a435362d3f1224d9ab6bf8928fe92ca50e244d

@adc-san

**Comment by adc-san** [comment]
Пропал интерфейс несоответствие

**Comment by adc-san** [comment]
Там опечатка в проверке - "mismathc" :)

**Comment by ADC-Andrei** [comment]
> Пропал интерфейс несоответствие

У меня нет)

**Comment by Neolined** [comment]
Исправил опечатку: 91cd59aa2c209bcadb09c3e36ce607935d39654a

**Comment by Neolined** [comment]
Исправил еще раз: 8c9c231425172977caed57ae18c6e4178f1f95bb
Видимо исправил в папке GitHub, а не в папке сервера

@adc-san

**Comment by adc-san** [comment]
> > Пропал интерфейс несоответствие
> 
> У меня нет)

Я в нашей базе стараюсь держать более-менее рабочую версию. Если большой баг обнаруживаю, то откатываю на предыдущую или, если могу исправляю, пока Денис чинит
