### ISSUE TITLE
Уязвимость для SQL injection

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#55]
В accept.php присутствует такой вызов:

`mysqli_query($link, "select `type` from `list_of_products` where `type` = '".$_POST['type']."'");`

Насколько я понимаю, это делает код уязвимым для SQL injection, так как значение type, полученное из запроса POST, добавляется в SQL запрос без каких-либо проверок и преобразований. Аналогичную проблему вижу с полями name и serial.

Предлагаю все строковые значения, помещаемые в запросы SQL, предварительно обезопасить с помощью mysqli_real_escape_string(), например так:

`
mysqli_query($link, "select `type` from `list_of_products` where `type` = '".mysqli_real_escape_string($_POST['type'])."'");
`

**Comment by alx4** [comment]
@adc-san, тэг Bug, я думаю, здесь тоже не помешает. :)

**Comment by Neolined** [comment]
Сделано: c9a4774ac9dca5d8f01bdfbff294b0bb209bd8c9
Везде, где были запросы к бд, обработал переменные подставляемые в запросы с помощью функции mysqli_escape_string.
Также исправил "баг" в "Ремонте" - после ввода двух серийных друг, за другом, после нажатию на кнопку "далее", серийные сменяли друг друга сами.
Удалил столбцы "ПО" и "Вхождение" из "Тестирования"

**Comment by Neolined** [comment]
Исправлены ошибки, когда отправленные данные требуется отобразить для последующих изделий, либо в ремонте после записи диагностики ее отобразить, возникала проблема после отправки данных, значения с кавычками отображались уже экранированными из-за функции mysqli_escape_string, приходилось бы вручную исправлять значения в полях.
Исправлено: a24208d5ee640bfb2244de0f143855a3246bcbef

**Comment by adc-san** [comment]
Денис, почитай комменты Алексея к коммитам, кажется ещё не всё сделано:
c9a4774ac9dca5d8f01bdfbff294b0bb209bd8c9
a24208d5ee640bfb2244de0f143855a3246bcbef

**Comment by Neolined** [comment]
Прочитал, исправил: cc06bd4bb30248f44d18f496a398b25940b0818e

@adc-san

**Comment by Neolined** [comment]
Забыл убрать отладочные сообщения.
Убрал здесь: 44a38fa102df7c58dc3e449d2213eed3f4dbdbbf

@adc-san

**Comment by adc-san** [comment]
Алексей, есть ещё замечания по этому тикету?

**Comment by alx4** [comment]
> Алексей, есть ещё замечания по этому тикету?

Саша, я весь код не анализировал, поэтому не знаю, все ли уязвимости устранены или нет. Я открыл самый первый файл (accept.php), и мне сразу бросилось в глаза, что данные извне передаются в запрос. О чем я и поспешил сообщить в этом тикете.

Точно так же я просматривал коммит и заметил, что несколько мест было пропущено. Я не знаю, есть ли еще такие места. Например есть переменная `$_SESSION`, в которую (мне) неизвестно какие значения попадают - "как есть" или уже обработанные mysqli_real_escape_string()...

**Comment by alx4** [comment]
Посмотрел более внимательно. Нет, к сожалению, не все уязвимости устранены. В [main.php](https://github.com/Neolined/DatabaseADC/blob/44a38fa102df7c58dc3e449d2213eed3f4dbdbbf/main.php#L98) в SQL запрос передается `$_POST['history']` без каких-либо преобразований и проверок.

**Comment by Neolined** [comment]
Не подумал, что пользователь может подменить у selecta (html) значение. 
Исправил: 3fd1f7c3fa67ce6824458ef9d8e0766edf44d22e
Escape-нул значения передаваемые в запросе в main.php: $_POST['history'], $_SESSION['order'], и $_SESSION['request'] (в библиотеке lib\main.lib.php, в функции requestDB, через которую переменная создается)
Escape-нул значения передаваемые в запросе в otk.php, repair.php, testing.php: $_POST["status"]
Исправил отображение в main.php - после выбора фильтров, и нажатия применить, сортировка была по `uid`-у по возрастанию, а не по убыванию

@adc-san 
@alx4

**Comment by adc-san** [comment]
@alx4 

Алексей, мне нужно твоё мнение, раз ты уж открыл этот тикет :-)
Можно закрывать, или уязвимости ещё остались?

**Comment by alx4** [comment]
> Можно закрывать, или уязвимости ещё остались?

Хорошо, сделаю очередную попытку ревизии кода...

1. Значение `$_SESSION['worker']` не везде искейпится (скорее, почти нигде). 
1. `$_POST['history']` не везде искейпится.

Думаю, достаточно. Уязвимости еще остались.

**Comment by Neolined** [comment]
Сломалась кнопка "Сбросить фильтры" на Главной: 
Исправлено: 4dcd23054147199f160ba733e466fa14bcd1c81e

@adc-san

**Comment by adc-san** [comment]
Предлагаю вернуться к вопросу после выполнения #77

**Comment by adc-san** [comment]
Итак, #77 выполнен.
Алексей, предлагаю тебе, как автору тикета, снова проверить остались ли уязвимые места для иньекций.

**Comment by alx4** [comment]
> Алексей, предлагаю тебе, как автору тикета, снова проверить остались ли уязвимые места для иньекций.

Насколько я вижу - да, остались. Например [здесь](https://github.com/Neolined/DatabaseADC/blob/390a2b793c7a287b28f4c6cdec4d332f781db34c/lib/main.lib.php#L165) текст из запроса HTTP напрямую попадает в запрос SQL.

**Comment by Neolined** [comment]
Исправлено: 0ce175248fdecefdf3de89e17664f93b54d91bc3
@alx4
@adc-san

**Comment by adc-san** [comment]
Перенёс: https://trac.adc-line.ru/mc-04/ticket/879#ticket
