### ISSUE TITLE
Интерфейс "Возврат" оптимизация

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#57]
Так получилось, что интерфейс возврат сейчас используется для передачи плат со Склада в другую локациию.
Например, когда на производство поступает заказ Оля набирает на складе платы и выдаёт их испытателям, для проверки и сборки заказа. Обычно изделия у неё идут группами по несколько одинаковых, например 10 корзин, 10 плат SW-01, 12 плат питания и т.д. Т.к. платы набраны на складе номера идут в разброс, а в базе плат ещё нет, и поэтому чтобы передать 10 плат SW-01 на производство ей нужно 10 раз заполнять в форме Возврат все поля : Тип, Название изделия, Исполнение, "От кого",Местоположение, хотя для этих 10 плат все поля будут совпадать, отличаться будет только серийник.
Думаю ей было бы гораздо удобнее если предыдущие введённые данные оставались при следующем вводе.

Предлагаю после записи в БД информацию из всех полей(или поля "От кого" и "Местоположение"если плата уже была в базе) куда-то запомнить, и при вводе нового серийника и нажатии Далее, передать эту информацию через запрос вместе с серийником, и затем, если платы в базе нет, заполнять ВСЕ известные поля как они были в предыдущем запросе, а если плата в базе есть заполнить имеющиеся поля "От кого" и "Местоположение".

**Comment by Neolined** [comment]
Улучшено: e9a289ee7462a76230df3c071324e021b40bf5c3

@adc-san

**Comment by adc-san** [comment]
1. Есть небольшая ошибка - поле Исполнение заполняется данными из Имя
2. Поле Комментарий тоже было бы хорошо передать

**Comment by alx4** [comment]
По моему опыту работы в другой компании: когда платы первый раз заносятся в базу данных, то, как правило, поступает сразу большая партия плат, а запись для всех делается одна и та же: "плата поступила из монтажа". Партию в 200 плат трудно вводить в базу по одной даже если требуется всего пара нажатий. На этот случай у нас был предусмотрен ввод сразу группы плат: указывался комментарий и количество плат, и по одному нажатию кнопки в базу добавлялось сразу 200 плат, после чего возвращались их серийные номера (там серийные номера генерировались системой, а как у нас сейчас - я не знаю)...

**Comment by adc-san** [comment]
>сразу 200 плат
Такая возможность есть в интерфейсе Приёмка, который предназначен для первичного занесения плат в базу.

Но в процессе выяснилось, что иногда нужно некоторое количество плат, с уже наклеенными серийниками со склада куда-то передать, но при этом плат в базе ещё нет (т.к. сейчас переходный процесс и не все платы со  склада ещё попали в базу).  И чтобы на время этого переходного процесса(неизвестно сколько он будет длиться) не делать для одной платы сначала Приёмку а затем Передачу, я попросил Дениса расширить возможности интерфейса Возврат.

**Comment by Neolined** [comment]
Исправил в этом коммите: 44a38fa102df7c58dc3e449d2213eed3f4dbdbbf

@adc-san
