### ISSUE TITLE
На Главной по умолчанию сортировать таблицу по UID в обратном порядке

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#60]
Сейчас если только зашел на Главную и ещё не применял фильтр/сортировку, то таблица отсортирована по UID, от старых записей к новым.
От пользователей поступило предложение выводить таблицу по умолчанию(пока к ней явно не применена сортировка), отсортировав по UID от новых к старым, т.е. в обратном порядке.
Это позволит сразу, без лишних нажатий, увидеть в таблице свежие записи и проверить что при вводе не допустили ошибок.

**Comment by Neolined** [comment]
Улучшено: b4002a261838c95b7560efa9564a7c629fa563d4
Сортировка на главной по умолчанию теперь по UID в обратную сторону
