### ISSUE TITLE
Всплывающие подсказки в процессе ввода текстовых строк

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#61]
По опыту эксплуатации подобной системы в другой компании могу сказать, что очень легко допустить ошибку (или даже не ошибку, а просто использовать разные регистры символов) при вводе текстовых строк. Например уже сейчас я вижу в некоторых текстовых полях таблиц значения "АДС" и "адс"... Также часто бывает, что требуется ввести значение, которое ранее уже вводилось и присутствует в базе (например наименование покупателя, который ранее уже что-то покупал).

В подобных случаях очень помогает функция всплывающей подсказки, которая появляется в процессе набора текста в текстовом поле и показывает варианты значений, уже имеющихся в базе и содержащих введенный фрагмент текста.

Например, при вводе пользователем в поле "покупатель" символов "**на**" выскакивает подсказка со значениями "**На**примеров А. С.", "ООО "**На**ша жизнь"", "АО Ка**на**рские острова" и т.п, и пользователь может выбрать один из этих вариантов для вставки в редактируемое поле. Это не только экономит время пользователя, но еще и позволяет уменьшить вероятность ошибки, когда одно и то же название вводится по-разному ("АДС"/"адс").

**Comment by adc-san** [comment]
На самом деле в некоторых местах такие подсказки уже используются, нужно просто сформулировать в каких ещё полях они нужны. Заберу пока это предложение к себе, на обдумать.

**Comment by adc-san** [comment]
Подсказки должны работать, т.е. нужно запросить в базе все варианты заполнения этого поля и при наборе букв предлагать пользователю готовые варианты в выпадающем списке (примерно как поля Название и Тип в интерфейсе приёмка) Но естественно эти подсказки не должны ограничивать пользователя в заполнении полей, как те самые Имя и Тип, это всего лишь подсказки.

Подсказки нужны в следующих полях:
Приёмка:  От кого
Возврат:  От кого
ОТК:  UID заказа

**Comment by Neolined** [comment]
Сделано в:
80e1ba9c3e61c9f7101bd1cdebc6d35ec044056c

@adc-san, @ADC-Andrei

**Comment by alx4** [comment]
Обьратите внимание, что реализованное автодополнение работает не так, как в моем [примере](https://github.com/Neolined/DatabaseADC/issues/61#issue-897765553): "ООО "Наша жизнь"" и "АО Канарские острова" не выскакивают при вводе "на".
