### ISSUE TITLE
Тестирование: Ошибка при записи.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#62]
Пользователи жалуются, что при записи через интерфейс тестирование иногда возникает ошибка:
> Error recording in table history:Incorrect integer value: '' for column `adcproducts`.`history`.`UID` at row 1

UID в обоих базах одинаковые, возможно есть какая-то ошибка при получении UID из products
Проверяли кажется на этой версии: https://github.com/Neolined/DatabaseADC/commit/ee4bac903aea18d3b2d51a28775fca6947b0b173

**Comment by Neolined** [comment]
Исправлено: 218ebac18e855aec35dca7339d00425b237cbf73
Скорее всего ошибка возникала при из запроса "select * from products where serial".
Исправил на "select `uid` from products where serial"
P.S. после запроса выполнялось присвоение переменной $row = mysqli_fetch_row и после SESSION['uid']-у присваивалось значение $row[0]. Как я думаю, что $row[0] при определенных условиях, было не `UID`-ом, а значением из другого столбца.

**Comment by adc-san** [comment]
Попросил тестировщиков понаблюдать, будет ли проявляться баг теперь.
