### ISSUE TITLE
Главная. Фильтр по серийному номеру

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#64]
Вижу что нужен фильтр по серийному номеру. Строка ввода в которую можно ввести часть серийного номера и отфильтроваться должны все изделия содержащие в серийнике введённую строку. 
Естественно вести себя этот фильтр должен как остальные, применяться совместно с другими и запоминать значение

**Comment by adc-san** [comment]
В случае реализации #67 п. 2a нужен будет фильтр по нескольким серийникам сразу
поэтому предлагаю расширить задание:

Фильтр по серийникам - поле ввода, которое может содержать несколько подстрок, перечисленных через запятую, или одну подстроку. Каждая подстрока может содержать целый серийный номер или его часть.
Примеры содержимого:
`C12345`
`С1`
`C12345,C12346,C12347`
`C,D,E,1234`
В выводе фильтра должны присутствовать все изделия которые содержат в серийном номере любую из подстрок. Важный момент - изделия должны быть выведены только один раз(например если фильтр = `1,2`, то изделие с номером `C12345` совпадёт и с первой подстрокой и со второй, но в таблице на главной оно должно быть выведено только один раз.
В идеале этот фильтр должен применяться с другими фильтрами и сортировкой.

**Comment by Neolined** [comment]
Сделано: 4e4031bb68b95ed55f660d1a2c09d57aabecc09d

@adc-san
