### ISSUE TITLE
Порядок позиций внутри фильтра

### ISSUE THREAD

**Issue by ADC-Andrei** [Neolined/DatabaseADC#65]
Мне было бы значительно удобнее, если бы в фильтрах позиции были упорядочены, например, по алфавиту.
Иначе достаточно сложно искать нужную плату.

**Comment by adc-san** [comment]
Согласен, сложно найти нужный фильтр, когда они вразнобой.
В первую очередь речь о группе фильтров "Название"

**Comment by Neolined** [comment]
Сделал: 62be9047dd539f60ad327ddbdd771a1d0e574440
С фильтрами, которые переведены на русский сложнее, потому что сортировка указывается в запросе в базу, а оттуда извлекается массив со значениями на английском, отсортированный по алфавиту, и далее обработчиком переводится. Думаю, что это сделать не так легко, но если нужно сделаю. Нужно? 

@adc-san

**Comment by adc-san** [comment]
Думаю что хватит этого, там где переведено, там вариантов мало и они все перед глазами, проблемы поиска нет.
