### ISSUE TITLE
Заказы. Исправить форматирование и добавить ссылки.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#67]
1. Исправить форматирование таблицы - строка вылезает наружу из таблицы, когда другие ячейки не заполнены, нужно чтобы она переносилась на следующую.
![Безымянный](https://user-images.githubusercontent.com/36914827/119640193-cacc6580-be31-11eb-81f3-6a60753e2973.png)

2a. Нужно в номере заказа сделать ссылку, при клике по которой, открывается Главная с применёным фильтром, в котором прописаны все серийники плат из заказа, тогда весь заказ будет сразу удобно виден пользователю, тем более в #64 уже должен быть сделан фильтр по серийнику.

2b. если вдруг 2a будет сложно реализовать, то нужно сделать хотябы временный вариант - из серийных номеров сделать ссылки. чтобы по клике на серийный номер открывалась история изделия на главной (найти в базе по серийнику UID и открыть его историю). Если 2a получится. тогда 2b не нужно делать.

**Comment by Neolined** [comment]
Сделано : 3c22b16ef5589345fa35e62705435a372b9f75d8
Добавил возможность перехода по номерам заказов на главную, где отображаются изделия, входящие в состав заказа. 
Насчет того, что серийные номера не переносятся на другую строку. Если серийные номера записаны через запятую - не переносятся, а если через запятую и пробел переносятся. Я изменил код так, чтобы серийные номера, записывались в таблицу через запятую и пробел и извлекались соответствующим образом. Предлагаю, пока еще записей не много, поставить пробелы у серийных номеров в столбце `composition`, в тб "Заказы". 
В ином случае, если сделать перенос символов, то они обрезаются неравномерно, например: 
"C08955, C08955, C08
955 C08955 C08955 C
и т.д" 

@adc-san

**Comment by adc-san** [comment]
С переносом символов понятно, меня устраивает. Добавил пробелы в созданные заказы.
Переход по ссылке работает замечательно, но есть одно замечание. Было бы значительно удобнее, если бы, после перехода по ссылке, список серийников был помещён в поле соответствующего фильтра, тогда пользователь бы смог потом отфильтровать заказ глубже, например увидеть все Платы SM-02, или отобразить количество и т.д.

**Comment by alx4** [comment]
> Я изменил код так, чтобы серийные номера, записывались в таблицу через запятую и пробел и извлекались соответствующим образом.

Извините что вмешиваюсь не совсем по  теме тикета, но хорошо ли вообще, что состав заказа хранится в базе данных в форме текстового перечисления, то есть неструктурировано? Как в таком случае, например, SQL запросом получить заказы, в которых присутствует некое изделие? Не будет ли лучше хранить состав заказов в форме таблицы?

**Comment by alx4** [comment]
Вдогонку к предыдущему комментарию: еще минусы неструктурированного хранения состава заказа я вижу в том, что нет никакой минимальной проверки сохраняемых данных на валидность. Например можно записать в поле orders.composition несуществующий серийный номер, или записать один и тот же серийный номер несколько раз... СУБД у вас эти ошибки не отследит, так как сейчас для нее состав заказа - ничего не значащий текст...

**Comment by adc-san** [comment]
@alx4 
Сейчас "Заказы" это скорее набросок, тестовая версия, чтобы на практике понять что нам вообще нужно.
Предлагаю продолжить обсуждение в #74

**Comment by Neolined** [comment]
> С переносом символов понятно, меня устраивает. Добавил пробелы в созданные заказы.
> Переход по ссылке работает замечательно, но есть одно замечание. Было бы значительно удобнее, если бы, после перехода по ссылке, список серийников был помещён в поле соответствующего фильтра, тогда пользователь бы смог потом отфильтровать заказ глубже, например увидеть все Платы SM-02, или отобразить количество и т.д.

Ты имеешь ввиду, чтобы после нажатии на номер заказа и перехода на главную, были выбраны чекбоксы соответствующие?

**Comment by adc-san** [comment]
Хм.. действительно передаётся. Видимо я провёл эксперимент с ошибкой, может быть не обновил скрипт JS, или ещё что-то перепутал. Извиняюсь)
