### ISSUE TITLE
При неуспешном ОТК устанавливать несоответствие

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#68]
В интерфейсе ОТК, когда выбран вариант otk=fail при записи нужно установить в products->mistmach=yes

**Comment by Neolined** [comment]
Исправлено: 572efc1b55b7ca4c84b260ae9f203269591ef424
В интерфейсе ОТК, когда выбран вариант otk=fail при записи устанавливается в products->mistmach=yes

**Comment by Neolined** [comment]
Сломалась кнопка "Сбросить фильтры" на Главной:
Исправлено: 4dcd230

@adc-san
