### ISSUE TITLE
Развалилась История на главной

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#69]
При нажатии кнопки показать историю возникает ошибка:
`Ошибка запроса: mysqli_queryYou have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ') and () and () order by `uid` desc' at line 1`

**Comment by adc-san** [comment]
проверял в 62be9047dd539f60ad327ddbdd771a1d0e574440

**Comment by Neolined** [comment]
Решена беда здесь: 4a6fc84
@adc-san
