### ISSUE TITLE
ОТК. Ошибка при записи.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#70]
Женя сообщил, что при попытке записи ОТК у него возникла  ошибка:
`Ошибка записи в ТБ история:Incorrect integer value: '' for column `adcproducts`.`history`.`UID` at row 1`
Это выглядит похожим на #62

Серийный номер он не вводил руками а скопировал в поле ввода, это единственное что можно считать особым в этой операции, хотя какая разница.
Проверял в 44a38fa102df7c58dc3e449d2213eed3f4dbdbbf

**Comment by Neolined** [comment]
Решена беда здесь: 4a6fc84
Уверен, что перед тем как он копировал, он обновил или просто открыл другую страницу, с которой собственно и скопировал, поэтому запрос не зашел.
@adc-san
