### ISSUE TITLE
Ссылки в ячейках на главной

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#71]
По заявке производства возникло следующее предложение.

На главной содержимое некоторых ячеек преобразовать в ссылки:
- при клике на ячейку Местоположение - открывать интерфейс Возврат с введённым серийником находящегося в строке изделия.
- при клике на ячейку ОТК - открывать интерфейс ОТК с введённым серийником.
- при клике на ячейку Тестирование - открывать интерфейс Тестирование с введённым серийником.
- при клике на ячейку Местоположение - открывать интерфейс Возврат с введённым серийником.
- при клике на ячейку Ремонт - открывать интерфейс Ремонт с введённым серийником.
- при клике на ячейку Несоответствие - открывать интерфейс Несоответствие с введённым серийником.

**Comment by Neolined** [comment]
Исправлено: c453f4f94201d78b4f31d404cf35e9f30ad2314f
Добавил ссылки на главную в ячейки столбцов: "Местоположение", "ОТК", "Тестирование", "Ремонт", "Несоответствие"
@adc-san
