### ISSUE TITLE
Главная. Повысить информативность отображения таблицы.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#72]
Из-за длинных названий некоторых столбцов в таблице на главной, таблица сейчас слишком растянута по ширине.
С целью повышения информативности отображения предлагаю изменить названия некоторых столбцов:

Наименование -> Имя
Исполнение -> Исп.
Серийный номер -> S/N
Тестирование -> Тест
Несоответствия -> Несоотв.

p.s. Выбрал те столбцы названия которых обычно длиннее содержимого.

**Comment by alx4** [comment]
Дополню еще одним предложением. С той же целью (повышения информативности отображения) предлагаю на этой же странице из стиля `#history` удалить `height: 3em;`,  а в стиле `.table td` уменьшить значение `padding`
 с 7px до 4px. Это значительно сократит промежутки между строками (особенно по вертикали) и позволит в несколько раз эффективнее использовать площадь дисплея. Сейчас промежутки между строками тексте в 3 раза больше высоты символов, то есть 75% пространства по вертикали - пустое место. 

Было:
![before](https://user-images.githubusercontent.com/84128875/119818990-4f3de780-bf09-11eb-9052-3d694cfd1630.jpg)
Станет:
![after](https://user-images.githubusercontent.com/84128875/119819047-62e94e00-bf09-11eb-91f7-8eed5b282d59.jpg)

**Comment by Neolined** [comment]
Улучшено: c91571c4e3a10e1379e3b7a67bd326da2f8e930b

@adc-san 
@alx4

**Comment by adc-san** [comment]
Отлично вышло, добавлю ещё пару улучшений в этот же тикет:
1. Кнопку "Показать историю изделия" переименовать в "Показать"
2. Столбец Комментарий поменять местами с историей, поместить его в конец (там редко что-то будет и мало кому интересно)
3. Благодаря уменьшению высоты строк в экран теперь влазит больше и мне хотелось бы на страницу поместить побольше строк, скажем 30 вместо 20

**Comment by ADC-Andrei** [comment]
> 1. Кнопку "Показать историю изделия" переименовать в "Показать"

Предлагаю "История"

**Comment by adc-san** [comment]
> Предлагаю "История"

Там столбец уже назван История, ну можно и История, я не против.

> 3. Благодаря уменьшению высоты строк в экран теперь влазит больше и мне хотелось бы на страницу поместить побольше строк, скажем 30 вместо 20

Саша Пепеляев предложил ещё улучшить, добавить внизу кнопочку, 20 | 30 | 50 | 100
Чтобы пользователь сам выбрал сколько максимум в странице, хранить это в сессии.

**Comment by Neolined** [comment]
Изменено: d9d532599b7c1248d8e1e8f4b95aa0e365a2bc7d
1. Кнопка "Показать историю изделия" переименована в "История"
2. Столбец "Комментарий" поменяны местами со столбцом "История"
3. Справа. внизу страницы расположены значения "20|30|50|100" - выбор сколько строк из таблицы отображать.
@adc-san 
@ADC-Andrei
