### ISSUE TITLE
Разное поведение фильтров

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#73]
Я заметил, что содержимое фильтров Серийный номер, Количество и Склад при переходе на другую страницу и возврате обратно на Главную пропадает, а содержимое остальных фильтров остаётся.
Такое поведение фильтров неинтуитивно для пользователя, все фильтры должны вести себя одинаково.
4a6fc84ad69d3bfe5b2152fdbd6491db66a02fc4

**Comment by Neolined** [comment]
Исправлено : 6d35353f6d7a5c2e3214100e87710ce19c16906f
Теперь фильтры ведут себя одинаково
@adc-san
