### ISSUE TITLE
Как хранить Заказы

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#74]
@alx4
> Извините что вмешиваюсь не совсем по теме тикета, но хорошо ли вообще, что состав заказа хранится в базе данных в форме текстового перечисления, то есть неструктурировано? Как в таком случае, например, SQL запросом получить заказы, в которых присутствует некое изделие? Не будет ли лучше хранить состав заказов в форме таблицы?
> Вдогонку к предыдущему комментарию: еще минусы неструктурированного хранения состава заказа я вижу в том, что нет никакой минимальной проверки сохраняемых данных на валидность. Например можно записать в поле orders.composition несуществующий серийный номер, или записать один и тот же серийный номер несколько раз... СУБД у вас эти ошибки не отследит, так как сейчас для нее состав заказа - ничего не значащий текст...

**Comment by alx4** [comment]
> Алексей, можешь привести пример, в каком виде по твоему разумно было бы хранить заказы?

Ну например как-то так:
```
CREATE TABLE `orders` (
`id` INT(32) NOT NULL,
`created` TIMESTAMP NOT NULL DEFAULT NOW,
`status` ENUM('created','prepared','shipped'... whatever...),
`shipped` TIMESTAMP DEFAULT NULL,
 `recipient` VARCHAR(100),
`comment` TEXT,
... whatever ...
PRIMARY KEY `id`,
);

CREATE TABLE `order-items` (
`order_id` INT(32) NOT NULL,
`serial` VARCHAR(100) NOT NULL,
UNIQUE KEY (`order_id`,`serial`),
FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
FOREIGN KEY (`serial`) REFERENCES `products` (`serial`) ON DELETE RESTRICT
);
```
> Примерно как сейчас сделаны записи в истории для изделия? На каждый заказ N записей в таблице, где N количество изделий в заказе.

Да, примерно так. С той лишь разницей, что у заказа есть еще и собственные данные (статус, дата создания, дата отгрузки и т.п.), поэтому для их хранения есть еще одна таблица (orders в моем примере).

**Comment by Neolined** [comment]
Серийный номер из интерфейса ОТК записать в orders.composition нельзя, он проверяется, в базу через консоль можно. 
Проверку на существование серийного номера сделать можно.
Так что хоть какая-то, но минимальная проверка отчасти есть. Хотя для СУБД это ничто, как вы сказали
@alx4

**Comment by adc-san** [comment]
> есть еще одна таблица (orders
Такая таблица уже есть в базе, осталось добавить к ней order-items и постепенно перейти в интерфейсах на использование её.
