### ISSUE TITLE
О хранении данных из полей ввода в сессиях

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#75]
В продолжение устного разговора.
Насколько я понял, те данные которые пользователь вводил в поля формы, Денис сохраняет в сессиях, причём для каждого интерфейса создаётся своя сессия для пользователя .
Не совсем понимаю зачем так делать) ведь после нажатия кнопки отправить, все данные из полей формы будут отправлены в POST запросе и скрипт их оттуда может получить, зачем ещё куда-то сохранять?

@alx4 @Neolined

**Comment by alx4** [comment]
> Не совсем понимаю зачем так делать

У меня возник тот же вопрос. :) Но я постеснялся его задать. :)

**Comment by alx4** [comment]
Также странно, что иногда при записи в БД часть записываемых данных берутся из запроса, а другая часть - из $_SESSION. Например [здесь](https://github.com/Neolined/DatabaseADC/blob/6d35353f6d7a5c2e3214100e87710ce19c16906f/otk.php#L20) номер заказа берется из запроса, а серийный номер - из $_SESSION. А в $_SESSION он был записан в каком-то из предыдущих запросав. А откуда известно, что новый запрос желает записать тот же серийный номер, что и текущий?

Представим ситуацию:
1. Пользователь открывает сразу несколько страниц с данными нескольких разных плат.
2. Пользователь нажимает "Submit" в первой форме. Данные платы записываются в БД и серийный номер записывается в $_SESSION.
3. Пользователь нажимает "Submit" на другой странице. Выполняется запрос, где в новый ордер, введенный в форме, добавляется серийный номер из первой страницы...

По-моему, здесь имеет место race condition...

**Comment by adc-san** [comment]
По поводу необходимости Денис мне объяснил устно:
В некоторых интерфейсах, например Возврат - есть такой сценарий:
1. Пользователь заполняет много полей - нажимает кнопку 
2. Скрипт получает POST с многими параметрами, скрипт делает своё дело, записывает в базу сообщает об успехе и выводит только поле серийника и кнопку
3. По новому нажатия кнопки передаётся только серийник (т.к. в этой форме больше ничего нет)
4. Скрипт получив серийник через пост отрисовывает остальные поля формы и должен для удобства ввода(часто вводят подряд однотипные задачи) заполнить их значениями введённые пользователем в предыдущий раз, но в POST их уже нет, там только серийник.

Поэтому Денис придумал на этапе 2. сохранять все значения полей в "подсессию" (это такая сессия, но отличная от основной, которая используется для авторизации, на каждый интерфейс создаётся своя подсессия). Решение сложилось исторически как снежный ком :-) но исходная мысль была куда-то сохранить данные которые будут нужны, но не уходят в POST

Разговаривая с Денисом, я подумал, что, чтобы сохранить данные, можно было бы каким-нибудь способом таки засунуть их в POST вместе с серийником.
Алексей(@alx4 ), может ты предложишь более изящное решение исходной проблемы?

**Comment by alx4** [comment]
> ...заполнить их значениями введённые пользователем в предыдущий раз,

Здесь, как мне кажется, будет расхождение в понимании пользователем и сервером, что такое "предыдущий раз". :)

С точки зрения пользователя "предыдущий раз" - это то, что отправляли ранее **с этой же страницы/вкладки**, которая вот сейчас открыта в браузере (назовем это инстанцией интерфейса). Для сервера же "предыдущий раз" - это предыдущий запрос в рамках той же самой "подсессии", при этом запрос мог быть вызван нажатием кнопки на другой вкладке, в другом браузере, наконец, в другом компьютере (смартфоне например). Так как "подсессия" общая для одного интерфейса, то разные инстанции этого интерфейса будут разделять общие данные в ней. Поправьте, если я понимаю неправильно.

> Алексей(@alx4 ), может ты предложишь более изящное решение исходной проблемы?

Нет, не могу. Я бы делал ровно так, как ты и предлагаешь - засунул бы **все** необходимые данные в форму, чтобы любой запрос POST был самодостаточным, то есть содержал все необходимые данные.

**Comment by alx4** [comment]
Вдогонку к предыдущему комменту: то есть более правильным мне кажется хранить эти данные вообще не на сервере, а прямо в HTML-коде, открытом в браузере клиента. Пока страница открыта, юзер может формировать свои запросы, получая в ответ от сервера новую форму с теми же данными. Если же перешел на другую страницу (сменил интерфейс) - данные пропали, и тогда возвращаемся к пункту 1 и снова вручную заполняем много полей...
