### ISSUE TITLE
Фильтр Количество или Склад не возможно отключить

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#76]
Если ещё хоть один фильтр кроме количество склад включен, то убираешь галочку количество, нажимаешь применить, а количество появляется снова. Со складом тоже самое.
6d35353f6d7a5c2e3214100e87710ce19c16906f

**Comment by Neolined** [comment]
Исправлено: 402530bd3821ecc420c903e7739d5c2f4360230b
Теперь после снятия галочки у пунктов фильтра "Отображение" и нажатии кнопки "Применить фильтры", в ситуации, когда применены и другие фильтры, все работает исправно.

@adc-san
