### ISSUE TITLE
Хранить данные на стороне пользователя а не в сессиях

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#77]
Сейчас после получения данных через POST скрипт сохраняет их в сессию. Такой подход создаёт избыточность, race condition, и ещё некоторые проблемы.
Предлагается хранить данные в HTML-коде, открытом в браузере клиента. Иными словами засовывать все необходимые данные в форму, чтобы любой запрос POST был самодостаточным, то есть содержал все необходимые данные.
В таком случае пока страница открыта, юзер может формировать свои запросы, получая в ответ от сервера новую форму с теми же данными. Если же перешел на другую страницу (сменил интерфейс) - данные пропали, и тогда снова вручную заполняем поля.
Обсуждение вопроса было в #75

**Comment by Neolined** [comment]
Улучшено: e2aee161b0a24cd5de0d86bb0ccbd05cc1f6e6aa
Решил проблему перебивания данных и подобные проблемы, при открытии нескольких окон и др. условиях при которых использовалась одна сессия, отличным способом от предлагаемого, потому что предлагаемый требует больше времени и сил, а этот может быть временным вариантом, созданным в отдельной ветке. Способ решения вышеуказанных проблем заключается в присвоении id для сессии через функцию uniqid, которая создает уникальное значение. У подсессий id состоит из названия страницы + uniquid(), так что вероятность повторения id у сессий на разных страницах отсутствует, а на одной несколько раз открытой присутствует, но достаточно низкая.

@adc-san

**Comment by adc-san** [comment]
Два примера багов связаных с тикетом:
- один пользователь открывает главную страницу и видит что там применены фильтры, которые только что применил другой пользователь

- один испытатель, проверив плату, делает запись о проверке, а запись попадает в плату другого испытателя, который недавно тоже сделал запись о проверке(это серьёзно)

**Comment by adc-san** [comment]
Оля через Возврат создала в базе плату с серийным номером N1, затем некоторое время она базой не пользовалась а сегодня первым действием её было создать через Возврат в базе плату с номером N2, однако попытка закончилась ошибкой, причём в выводе ошибки присутствовал не N2, а старый N1

**Comment by Neolined** [comment]
Переход с сессий на хранение данных на странице пользователя:
ОТК: dce70fae4e1de59dbe77eff457ca2cfc9cc0fd7b

@adc-san @ADC-Andrei
