### ISSUE TITLE
Хранить содержимое заказов структурированно

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#78]
По мотивам обсуждения #74.
1. Предлагается создать дополнительную БД в которой будут храниться изделия включенные в заказ.
CREATE TABLE `order-items` (
`order_id` INT(32) NOT NULL,
`serial` VARCHAR(100) NOT NULL,
`parent` VARCHAR(100) NOT NULL,
UNIQUE KEY (`order_id`,`serial`),
FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE CASCADE,
FOREIGN KEY (`serial`) REFERENCES `products` (`serial`) ON DELETE RESTRICT
);
2. Добавить в ОТК кроме записи в orders->composition, параллельную запись сер.номеров изделий в новую таблицу
3. В интерфейсе Заказы отображать список номеров изделий входящих в заказ из таблицы order-items
4. В интерфейсе Отгрузка, получать список номеров изделий входящих в заказ из таблицы order-items
5. Убрать из ОТК запись в orders->composition 

План можно выполнить последовательно, за несколько коммитов не нарушая работоспособность интерфейсов.

**Comment by ADC-Andrei** [comment]
А зачем плодить БД?
Не достаточно ли добавить изделию набор полей, в которых будет записаны номера заказов.

**Comment by adc-san** [comment]
А зачем плодить поля) ? 
С полями будет реализовать заказы сложнее, т.к.:
- одна и таже плата может входить входить в несколько заказов
- в разных заказах у этой платы может быть разная входимость

**Comment by adc-san** [comment]
Добавил к order-items нужно добавить поле "входимость"  (parent) в котором указывается серийный номер изделия в которое установлено данное изделие в рамках этого заказа

**Comment by adc-san** [comment]
Перенёс в https://trac.adc-line.ru/mc-04/ticket/874
