### ISSUE TITLE
ОТК: Кажется номер заказа не записывается в history

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#79]
4a6fc84ad69d3bfe5b2152fdbd6491db66a02fc4

**Comment by Neolined** [comment]
Так. А куда его нужно записать? По-моему этого в ТЗ не было, поэтому не было никаких записей с номером заказа в историю.

@adc-san

**Comment by adc-san** [comment]
Да я и сам не помню :), возможно и в тз это упустили, лень проверять, однако в history есть поле number_order, логично что туда должен записаться

**Comment by Neolined** [comment]
Исправлено: ac93d430508809bad59eba3aa512ae03b6db8401
Теперь в историю записывается номер заказа, если он был указан в ОТК
@adc-san

**Comment by adc-san** [comment]
Посмотрел последние заказы,  в Истории нет ни одной записи с номером заказа, видимо и не записывается.
Понял. Коммит ушёл в какую-то ветку и в мэйн не попал.
