### ISSUE TITLE
Сортировка при фильтре "Склад" или "Количество"

### ISSUE THREAD

**Issue by ADC-Andrei** [Neolined/DatabaseADC#80]
На главной, если применить фильтры "Склад" или "Количество", то пропадает выбор сортировки по столбцам таблицы.
Предлагается дать пользователю возможность сортировать данные при использованию фильтров "Склад" или "Количество".

**Comment by adc-san** [comment]
Может это не баг а фича))
Она не то что не работает, её просто нет :-D
Может так и задумано. Изменил на улучшение.

**Comment by Neolined** [comment]
Сортировка изменена, теперь она доступна при применении фильтров количество и местоположение на главной, изменена сортировка в номенклатуре.
Улучшено: d2816003dee71e1d49c54e572c4d005e7f631385

@ADC-Andrei 
@adc-san
@alx4

**Comment by ADC-Andrei** [comment]
Проверил, работает
