### ISSUE TITLE
Главная страница: баг разбиения списка на страницы

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#81]
Главная страница отображает таблицу со списком изделий. Когда изделий много (а уже сейчас их сотни), список отображается страницами по частям. Будем условно нумеровать отображаемые записи начиная от 1 в том порядке, в каком они должны быть отображены.

Эксперимент.
1. Открываем в браузере главную страницу. Видим 20 изделий с 1 по 20.
2. Открываем еще одну главную страницу (в другой вкладке или другом браузере или даже на другом компьютере). Видим те же записи.
3. Кликаем по ссылке "100" в правом нижнем углу - визим 100 записей с 1 по 100. Теперь эту страницу можно закрыть.
4. Возвращаемся к первой странице, где по-прежнему видим записи с 1 по 20.
5. Кликаем по ссылке "2" для перехода на следующую страницу. Отображается 100 записей с 101 по 200.

С точки зрения пользователя, здесь сразу два бага:
1. Косметический: на второй странице отобразилось 100 записей, хотя **на этой вкладке** пользователь количество записей не менял, и ожидал увидеть следующие 20.
2. Серьезный: записи с 21 по 100 **были просто пропущены** - не были показаны пользователю вообще!

Причина такого поведения - сервер запоминает количество записей на страницу и позднее использует его для всех запросов в этой же сессии, даже если эти запросы инициированы из другой инстанции интерфейса - см. d9d532599b7c1248d8e1e8f4b95aa0e365a2bc7d

**Comment by adc-san** [comment]
Я думаю решить это через #77

**Comment by Neolined** [comment]
Исправлено в #77

@adc-san

**Comment by ADC-Andrei** [comment]
Теперь работает как ожидалось. Проверил на разных вкладках Мозилы.
