### ISSUE TITLE
Искаженное имя пользователя в правом верхнем углу страниц

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#82]
При наличии в реальном имени пользователя некоторых символов (апостроф, кавычки, бэкслеш) имя пользователя в правом верхнем углу каждой страницы выводится искаженным - с лишними бэкслешами:

![ss1](https://user-images.githubusercontent.com/84128875/120600662-78f39300-c462-11eb-9eec-c0f06cf5bf9b.jpg)

См. комментарий к 67ff72a46f4051dffddcb881642d2b83433f9bbb

**Comment by Neolined** [comment]
Теперь не экранируется имя пользователя: 48981bdcba2f85d22aed8f44e057d4f0fe5f48b0
@alx4 
@adc-san

**Comment by ADC-Andrei** [comment]
Алексей, если проблема решена, закрой пожалуйста тикет.
