### ISSUE TITLE
В POST передаются устаревшие данные

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#83]
Ранее Оля через Возврат создала в базе плату с серийным номером N1, затем некоторое время она базой не пользовалась а сегодня первым действием её было создать через Возврат в базе плату с номером N2, однако попытка закончилась ошибкой, причём в выводе ошибки присутствовал не N2, а старый N1

p.s. Кажется @alx4 упоминал возможность такой ошибки
нужно скорее делать #77 ...

**Comment by alx4** [comment]
Насколько я вижу, добавление записи в БД производится [здесь](https://github.com/Neolined/DatabaseADC/blob/402530bd3821ecc420c903e7739d5c2f4360230b/refand.php#L41). При добавлении записи используется серийный номер, который ранее был запомнен в сессии (а не тот, который прислали в запросе).

**Comment by adc-san** [comment]
Дублирует  #77 
(перенесу туда описание конкретного проявления бага)
