### ISSUE TITLE
На главной странице не отображается общее количество изделий

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#84]
На главной странице не отображается общее число изделий, удовлетворяющих условиям фильтра. Это не позволяет, например, узнать, сколько плат VE-02 имеется на складе.

Предлагаю отображать на главной странице общее число записей, удовлетворяющих условиям фильтра.

**Comment by Neolined** [comment]
Теперь на главной странице отображается общее число записей, удовлетворяющих условиям фильтра.
Добавлено: 716adab62d4af6b9d0069fd77e50795ee69dbff6

@alx4
@adc-san
@ADC-Andrei

**Comment by ADC-Andrei** [comment]
Проверил, На главной странице отображается общее число изделий, удовлетворяющих условиям фильтра.
