### ISSUE TITLE
Невозможно изменить реальное имя пользователя

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#85]
Сейчас пользователь вводит свое реальное имя лишь один раз при регистрации, и нет никакой возможности впоследствии это имя изменить. В то же время бывают случаи, когда человек меняет имя (не говоря уже о случаях, когда пользователь по ошибке неверно ввел свое имя, и эту ошибку невозможно исправить).

Предлагаю добавить пользователю возможность изменить свое реальное имя.

**Comment by adc-san** [comment]
Т.к. пользователей будет порядка 10, то можно изменить имя через администратора базы.
Не будем усложнять.
