### ISSUE TITLE
Предзаполнение поля комментария

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#86]
Страница "Возврат". Предлагаю предзаполнять поле "Комментарий" примерно таким текстом: `Изделие передано от <xxx> к <yyy>`, где **`<xxx>`** - значение поля "От кого", **`<yyy>`** - значение поля "location" (в веб-интерфейсе не подписано). При изменении значений указанных полей автоматически обновлять текст комментария. Это позволит экономить время сотрудника на ввод комментария и уменьшить вероятность записи ошибочного комментария.

**Comment by adc-san** [comment]
Это поведение - следствие неправильного хранения данных в сессиях, #77 должен это исправить.
Предложение по предзаполнению принял.

**Comment by adc-san** [comment]
Сообщение о баге перенёс в #77, отредактировал изначальный текст тикета. Улучшение оставил здесь.
Однако предложенный текст автозаполнения комментария мне не очень нравится, ведь по записи в истории и так должно быть понятно откуда и куда положено, на мой взгляд лучше добавить поле location в историю (#99).
Про автозаполнение комментариев нужно подумать, возможно в каких-то интерфейсах это будет полезно

**Comment by alx4** [comment]
> Однако предложенный текст автозаполнения комментария мне не очень нравится, ведь по записи в истории и так должно быть понятно откуда и куда положено,

Хм... Я думал, что этот комментарий как раз и будет записан в историю - то есть он и есть эта запись. Если я ошибался, то мне непонятно, куда записывается этот комментарий, и для чего он тогда нужен...

**Comment by adc-san** [comment]
Комментарий записывается в историю, всё правильно.
Но кроме коментария в историю записываются и другие поля, например От кого и в скором времени location(#93)
По значению этих полей должно быть понятно откуда и куда двигалась плата, а поле коментария лишь дополнение, в котором можно указать какие-то особенности данной записи

**Comment by alx4** [comment]
> кроме коментария в историю записываются и другие поля, например От кого и в скором времени location(#93)

А, тогда, действительно, в комментарии это дублировать нет смысла. Правда лично мне непонятно, почему именно для этой информации выделены отдельные столбцы в таблице... Что, например, должно быть в этих полях для такого комментария: "Вытер пыль с платы. Теперь выглядит как новая."? :)

**Comment by adc-san** [comment]
Столбцы выделены, т.к. большинство записей в истории в основном о передвижении плат, внутри компании или снаружи.

**Comment by Neolined** [comment]
Жду решения по этому вопросу. Делать дублирование или нет?

@adc-san

**Comment by ADC-Andrei** [comment]
> > кроме коментария в историю записываются и другие поля, например От кого и в скором времени location(#93)
> 
> А, тогда, действительно, в комментарии это дублировать нет смысла. Правда лично мне непонятно, почему именно для этой информации выделены отдельные столбцы в таблице... Что, например, должно быть в этих полях для такого комментария: "Вытер пыль с платы. Теперь выглядит как новая."? :)

Например, да. Или, например: "Резисторы R2 и R96 запаяли сами (были в дефиците)".

Саша, я не вижу применения предзаполнению комментария. Наверно можно закрыть тикет.

**Comment by alx4** [comment]
> Например, да. Или, например: "Резисторы R2 и R96 запаяли сами (были в дефиците)".

Ты, вероятно, не понял, что речь идет о поле location. Зачем записывать в поле location "Резисторы R2 и R96 запаяли сами (были в дефиците)"? Эта фраза ничего не говорит о местоположении...

**Comment by ADC-Andrei** [comment]
> > Например, да. Или, например: "Резисторы R2 и R96 запаяли сами (были в дефиците)".
> 
> Ты, вероятно, не понял, что речь идет о поле location. Зачем записывать в поле location "Резисторы R2 и R96 запаяли сами (были в дефиците)"? Эта фраза ничего не говорит о местоположении...

Да, я с именами полей не дружу))
