### ISSUE TITLE
Баг: в процессе работы внезапно получил ответ 403 Forbidden

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#87]
Столкнулся со следующим поведением - работаю с системой (просматриваю информацию об изделиях, перехожу со страницы на страницу), и вдруг при попытке открыть очередную страницу получаю ответ 403 Forbidden. Это сртранно и нелогично с точки зрения пользователя (только что было все можно, и вдруг стало запрещено). После повторной аутентификации страницы опять стали доступны.

**Comment by alx4** [comment]
Воспроизвел еще раз. Описываю действия.

1. Аутентифицируюсь, получаю список изделий на главной странице.
2. Оставляю открытой главную страницу более суток.
3. Кликаю ссылку в столбце "Местопол" - открывается форма "Возврат", хотя я ожидал ответ 403.
4. В браузере нажимаю "Назад" - и только теперь получаю ответ 403.

**Comment by Neolined** [comment]
Предлагаю сделать как: установить время сессии не ограничено.
И создать таймер, который после определенного времени бездействия пользователя, показывает сообщение, например, "Ваша сессия прекратиться через 1 минуту". Хотите ли вы продолжить?"
И если в течение минуты пользователь не нажмет на кнопку "Продолжить", то его перекинет на страницу авторизации.
Как идея?

@adc-san
@alx4

**Comment by ADC-Andrei** [comment]
А нельзя учитывать время бездействия?
И "выкидывать" при простое 2 часа, например.

**Comment by alx4** [comment]
1)
> установить время сессии не ограничено.
2)
> "Ваша сессия прекратиться через 1 минуту".

По-моему первое противоречит второму. :)  Насколько я понимаю, если время сессии не ограничено, то сессия не прекратится никогда.

> И если в течение минуты пользователь не нажмет на кнопку "Продолжить", то его перекинет на страницу авторизации.
> Как идея?

Не понимаю, в чем ее смысл. Разъясани, пожалуйста.

**Comment by alx4** [comment]
> А нельзя учитывать время бездействия?
> И "выкидывать" при простое 2 часа, например.

Насколько я понимаю, именно так сейчас и сделано (только время сессии не 2 часа, а 24 часа). Не помню, откуда я это помню :) (скорее всего, устно кто-то говорил). Именно поэтому я посчитал багом, что:
- в пункте 3 [моего сценария](https://github.com/Neolined/DatabaseADC/issues/87#issuecomment-865644458) открылась форма, хотя с последнего запроса прошло более 24 часов;
- в пункте 4 я получил ошибку 403 - крайне маловероятно, что 24 часа сессии истекли в тот враткий промежуток времени между п. 3 и п.4 (на форму "Возврат я смотрел всего секунд 10). Причем такой сценарий воспроизвелся у меня, как минимум, дважды.

**Comment by alx4** [comment]
> Как идея?

Я подумал над идеей. Считаю ее довольно бесполезной по следующей причине: если пользователь уже почти 24 часа не обращался к серверу, то крайне маловероятно, что он до сих пор продолжает смотреть на нашу страницу. :)  Скорее всего, он либо занялся другими делами (переключился на другие вкладки браузера) или вообще ушел. Поэтому даже если окошко будет выскакивать, вероятность, что пользователь посмотрит на открытую сутки назад вкладку ровно в ту минуту, когда там идет отсчет, стремится к нулю.

В веб-интерфейсе интернет-банка моего банка выскакивает подобное сообщение. Как показывает мой личный опыт, я почти никогда его не замечаю, хотя лимит сессии там всего 15-20 минут, а не 24 часа...

**Comment by adc-san** [comment]
Алексей, можешь повторить [эксперимент](https://github.com/Neolined/DatabaseADC/issues/87#issuecomment-865644458)?
Кажется теперь больше баг не воспроизводится.

**Comment by alx4** [comment]
> Алексей, можешь повторить [эксперимент](https://github.com/Neolined/DatabaseADC/issues/87#issuecomment-865644458)?

Попробую.

**Comment by alx4** [comment]
> Алексей, можешь повторить [эксперимент](https://github.com/Neolined/DatabaseADC/issues/87#issuecomment-865644458)?

Попробую. Эксперимент начался. :)

**Comment by alx4** [comment]
Эксперимент прошел успашно - я получил 403 на первый же запрос.
Завтра повторю эксперимент для большей надежности.

Меня смущает отсутствие каких-либо комментариев @Neolined по поводу этого бага. Когда и как он был исправлен? В чем была причина ложной авторизации?

**Comment by Neolined** [comment]
Как я понимаю эту ситуацию. В конфигурационном сервера сессия существует 24 часа. Пользователь авторизуется, оставляет страницу открытой, уходит домой, приходит на следующий день на работу и если прошло 24 часа, то при нажатии на любую кнопку из открытого интерфейса, при которой происходит отправка формы, то у пользователя появляется ошибка 403.
Ранее были ошибки с сессиями, у пользователей могли путаться сессии, как я помню на примере того, что один пользователь применил фильтры, у другого они применились на главной, если я все правильно помню. Механизм этого был не понятен мне, и по переходу с сессий на хранение данных на странице пользователя было ясно, что они исчезнут.

@alx

**Comment by alx4** [comment]
> Как я понимаю эту ситуацию. В конфигурационном сервера сессия существует 24 часа. Пользователь авторизуется, оставляет страницу открытой, уходит домой, приходит на следующий день на работу и если прошло 24 часа, то при нажатии на любую кнопку из открытого интерфейса, при которой происходит отправка формы, то у пользователя появляется ошибка 403.

Это ты описываешь, как **должно** быть. Я именно так эту ситуацию и понимал. Мой же вопрос был не в этом. Я хотел узнать, найдена ли причина, по которой в моем описанном выше эксперименте результат был не такой. Я так понял (возможно, неправильно) комментарий @adc-san, что реализация #77 автоматически решила и данную проблему. В то время как я между этипи проблемами не вижу никакой связи...

**Comment by adc-san** [comment]
По моим ощущениям это ещё до #77 починилось...

**Comment by alx4** [comment]
Только что воспроизвел баг с небольшим отличием от исходного. Описываю действия.
1. Вчера вошел в систему и приблизительно в 15:55 сделал последний запрос (главной страницы).
2. Сегодня в 16:00 нажал на ссылку в столбце "Местопол" и получил страницу "Возврат", хотя должен был получить ответ 403, так как с последнего запроса прошло более суток.
3. Вернулся на шлавную страницу - снова страница была успешно получена.
4. снова нажал ту же ссылку в столбце "Местопол", но на этот раз получил ошибку 403, хотя ее не должно было быть, так как после предыдущего успешного запроса прошло менее суток (несколько секунд).

**Comment by adc-san** [comment]
Перенёс: https://trac.adc-line.ru/mc-04/ticket/878#ticket
