### ISSUE TITLE
Улучшение: в интерфейсе Несоответствия показывать информацию о уже имеющихся несоответствиях изделия.

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#88]
В списке изделий на главной странице содержимое столбца "Несоотв." является ссылками, при клике которых открывается страница "Несоответствия" соответстсвующего изделия. Когда пользователь видит, что в столбце "Несоотв." какого-то изделия отображается ссылка "Да", он кликает эту ссылку, интуитивно ожидая увидеть подробности - что же и чему в этом изделии не соответствует. Однако на открывающейся по ссылке странице никаких комментариев о несоответствиях нет. Например изделие с серийным номером D02972 имеет несоответствие - "Клемник без стекла", что видно в истории изделия, но не видно при клике ссылки "Да" в столбце "Несоотв.".

Предлагаю отображать на странице, открывающейся по ссылкам в столбце "Несоотв.", показывать информацию о несоответствиях изделия.

См. также #71.

**Comment by Neolined** [comment]
Сделано: a3cc3ce0e955105294d160b6a509fddb985d2526
Теперь на странице в интерфейсе "Несоответствия", открывающейся по ссылкам в столбце "Несоотв." с Главной, показываться информация о предыдущих несоответствиях изделий.

@alx4
@adc-san
@ADC-Andrei

**Comment by ADC-Andrei** [comment]
Предыдущие несоответствия отображаются.
Алексей, если тебя устраивает такое представление интерфейса, закрой пожалуйста тикет.

**Comment by alx4** [comment]
> Предыдущие несоответствия отображаются.
> Алексей, если тебя устраивает такое представление интерфейса, закрой пожалуйста тикет.

Я никаких улучшений не наблюдаю. Вот что у меня открывается при клике "Да":
![ss1](https://user-images.githubusercontent.com/84128875/128459731-d2c016fd-7e47-4a3b-a801-1d97565459b4.jpg)

Как видите, никаких подробностей там нет.

**Comment by adc-san** [comment]
Дело в том, что флаг несоответствия может быть установлен в двух случаях:
1. Прямая запись через интерфейс Несоответствия
2. Запись через интерфейс ОТК не успешного прохождения ОТК

А во втором случае в историю не делается отдельная запись о несоответствии, а только запись о неуспешном ОТК
Предлагаю чтобы пользователю было понятно что не в порядке с платой а что уже починили, вывести сюда все исторические записи с типами: 'otk','mismatch','repair'.

**Comment by ADC-Andrei** [comment]
Если ОТК не принял плату, то в комментарии будет указано несоответствие. Вот его и нужно подтягивать сюда.
Но, нужно проверить ещё такой случай - добавить несоответствие с незаполненным комментарием.

**Comment by alx4** [comment]
> А во втором случае в историю не делается отдельная запись о несоответствии, а только запись о неуспешном ОТК

А вот это мне кажется уже неправильно. Получается, что, например, флаг несоответствия с изделия может быть снят, но по истории нельзя будет узнать, кто и когда его снял... Может быть **это** стоит изменить, например записывать две записи в историю?

**Comment by alx4** [comment]
И еще я заметил, что апдейт записи в products и добавление записи в историю - это две независимые транзакции. Таким образом, теоретически возможна ситуация, когда апдейт выполнился успешно, но запись в историю не выполнена.

Может быть имеет смысл выполнять это одной транзакцией?

**Comment by alx4** [comment]
> Предлагаю чтобы пользователю было понятно что не в порядке с платой а что уже починили, вывести сюда все исторические записи с типами: 'otk','mismatch','repair'.

Может лучше отображать **вообще всю** историю, мало ли что там может быть полезного в комментариях... А уже в веб-интерфейсе можно добавить кнопочки чтобы показывать/скрывать записи определенных типов...

**Comment by adc-san** [comment]
> Может быть имеет смысл выполнять это одной транзакцией?

Согласен, но это актуально не только для этого интерфейса, но и остальных.

>> А во втором случае в историю не делается отдельная запись о несоответствии, а только запись о неуспешном ОТК
> А вот это мне кажется уже неправильно. Получается, что, например, флаг несоответствия с изделия может быть снят, но по истории нельзя будет узнать, кто и когда его снял... Может быть это стоит изменить, например записывать две записи в историю?

По истории можно узнать, т.к. установить флаг можно записью несоответствия, неуспешным тестированием или неуспешным ОТК, а снять флаг можно только ремонтом или успешным ОТК(договорились мелкие косметические несоответствия, устранять без ремонта) и есть договорённость писать в комментариях что сломано ил что починили.
Вот, например изделие из твоего примера:
![image](https://user-images.githubusercontent.com/36914827/128511914-19af4cf3-a6da-403a-bf9f-0745e2d390d8.png)
На первом ОТК было обнаружено что проворачивается саморез, а на следующем отк выяснилось что нет уплотнительной резинки, когда изделие таки пройдёт ОТК успешно, это будет означать, что несоответствия устранили.


> Может лучше отображать вообще всю историю,

Не знаю, с одной стороны там может быть много лишних записей о перемещении изделия туда-сюда, а с другой стороны почему бы и нет...

**Comment by alx4** [comment]
> По истории можно узнать, т.к. установить флаг можно записью несоответствия, неуспешным тестированием или неуспешным ОТК, а снять флаг можно только ремонтом или успешным ОТК

А, кажется, я понял. Я не учел, что у записи ОТК есть еще признак "успешно"/"неуспешно".

**Comment by Neolined** [comment]
Улучшено в: 4870598ef78ded3697a63488ad39d9a400f6f688
 В интерфейсе несоответствия, помимо столбца `mismath` из истории, выводятся столбцы 'otk' и 'repair'.

@adc-san
@alx4

**Comment by adc-san** [comment]
Почемуто вывод истории работает не для всех изделий, проще будет показать, чем описать конкретику.

**Comment by alx4** [comment]
> проще будет показать, чем описать конкретику.

Показывай. :)

**Comment by adc-san** [comment]
https://trac.adc-line.ru/mc-04/ticket/871#ticket
