### ISSUE TITLE
Улучшение: показывать историю изделия по клику его серийного номера и/или имени

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#89]
В целях экономии места на дисплее предлагаю из таблицы на главной странице убрать столбец "История" с кнопками. Вместо этого сделать серийный номер и/или имя изделия ссылками, при клике которых и показывать историю изделия.

Это будет еще и удобнее в использовании, так как не надо будет тянуться мышью далеко вправо...

См. также #71.

**Comment by Neolined** [comment]
Улучшено: da89ece28db2e7d22253f7f75ff293880c17de1f
Теперь история показывается по клику его серийного номера

@ADC-Andrei
@alx4
@adc-san

**Comment by ADC-Andrei** [comment]
Действительно, показывается!
Позволю себе закрыть тикет.
