### ISSUE TITLE
Улучшение: расширить поле ввода комментария на странице ОТК

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#90]
На странице ОТК поле комментария имеет очень маленькую ширину, которую, к тому же, нельзя увеличить. При этом справа от этого поля есть много неиспользуемого места. Как результат, в такое поле неудобно вводить (и неудобно потом читать) комментарий, если он длиннее пары слов:

![ss1](https://user-images.githubusercontent.com/84128875/121342139-cbd5ba80-c93a-11eb-9bad-cb51d5247d07.jpg)

Предлагаю увеличить ширину поля ввода комментария, предоставав ему все свободное пространство справа:

![ss2](https://user-images.githubusercontent.com/84128875/121342706-57e7e200-c93b-11eb-9964-f942d5e5b398.jpg)

Также предлагаю сделать аналогичное изменение и на других страницах, имеющих поле комментария.

**Comment by Neolined** [comment]
Улучшено: 97b0602d2c1de5750bf7a6db76c68b67d4263b5a
Изменены стили для Mozila Firefox для однообразного отображения, как в других браузерах.

@alx4
@adc-san

**Comment by alx4** [comment]
> Изменены стили для Mozila Firefox для однообразного отображения, как в других браузерах.

Насколько я вижу, в стиле элементу textarea добавлена такая строчка:
https://github.com/Neolined/DatabaseADC/blob/97b0602d2c1de5750bf7a6db76c68b67d4263b5a/css/main.css#L132

Но ведь, насколько я понимаю, это свойство, дейтсвительно, будет действовать только в случае использования Mozila Firefox и его форков. А для других браузеров (которые не понимаю значения -moz-*) ширина элемента textarea так и останется не установленной! Таким образом, это получается лишь частичное решение проблемы...

Почему просто не установить элементу textarea `width: 100%`?

Или, как вариант, записать так:
```
width: 100%;
width: -moz-available;
```
тогда браузеры, понимающие -moz-available, будут использовать его, а не понимающие будут использовать 100%...

**Comment by Neolined** [comment]
![Безымянный](https://user-images.githubusercontent.com/80521325/127485254-a54293b3-8d5a-4c21-ad4e-c54075e89aad.png)
Проблема в том, что неравномерно отображаются по отношению к input при установке width в 100%, а если элементам внутри .form1 установить такую длину, то по отношению  к левому краю получается криво. В других браузерах, а именно Opera, Chrome, Edge, отображается нормально.
@alx4

**Comment by alx4** [comment]
> Проблема в том, что неравномерно отображаются по отношению к input при установке width в 100%, а если элементам внутри .form1 установить такую длину, то по отношению к левому краю получается криво, точнее длина от левого края и до окошка не равна длине от права края и до окошка.

Это все равно в 1000 раз лучше, чем на первом скриншоте!!! :)

> В других браузерах, а именно Opera, Chrome, Edge,

Это, фактически, один браузер. :)  Все перечисленные используют один и тот же движок.

> отображается нормально.

Странно...  А, понял. chrome берет `width: -webkit-fill-available` из класса `comment`. Тогда у меня возникает еще один вопрос: почему для chrome и его форков ширина поля определена [в одном месте](https://github.com/Neolined/DatabaseADC/blob/d561730d28e6ed9b5f22a00a60fadcf5bf56202d/css/main.css#L148), а для firefox и его форков - [в другом](https://github.com/Neolined/DatabaseADC/blob/d561730d28e6ed9b5f22a00a60fadcf5bf56202d/css/main.css#L132)?  Если это одно и то же свойство для двух назных типов браузеров, не логичнее ли устанавливаеть его в одном и том же месте?

Хорошо, для chrome, firefox и их клонов значение `width` указано. Но ведь все остальныы браузеры, которые не понимают ни `-moz-available`, ни `-webkit-fill-available`, по-прежнему будут использовать значение `auto`! Так почему бы не указать все три варианта: `width: -moz-available` для firefox, `width: -webkit-fill-available` для chrome и `width: 100%` как fallback для всех остальных (см. конеч моего [предыдущего комментария](https://github.com/Neolined/DatabaseADC/issues/90#issuecomment-888092245))?

**Comment by ADC-Andrei** [comment]
В хроме, мозиле, вивальде (вроде на хромиуме) все хорошо с полем для ввода комментария. Меня, как единственного ОТКшника, до сих пор это поле устраивало.
В ИЕ поле очень узкое и не имеет "уголка для растягивания". Но ИЕ я пользовать не собираюсь, а на роль ОТК в достаточно обозримой перспективе больше никто не претендует. 
Так что предлагаю закрыть и забыть.

Не, ну если вы тут из спортивного интереса дискутируете и для поиска истины, то ничего не имею против продолжения.

**Comment by alx4** [comment]
> Меня, как единственного ОТКшника, до сих пор это поле устраивало.

Насколько я понимаю, поле "Комментарий" имеется не только на странице ОТК, но и на других страницах тоже. И я подозреваю, что стили у всех этих полей сделаны одинаково. Таким образом, это не проблема только одной конкретной страницы. ОТК просто первой мне попалась мне на глаза, поэтому я и указал ее в тикете.

> Не, ну если вы тут из спортивного интереса дискутируете и для поиска истины, то ничего не имею против продолжения.

Не знаю, как другие, а я пишу сюда не из спортивного интереса, а делаю конкретное предложение по улучшению продукта. Если ты имеешь что-то против установки полям ввода fallback-значения ширины 100% - не стесняйся, высказывай свои аргументы.

**Comment by ADC-Andrei** [comment]
> > Меня, как единственного ОТКшника, до сих пор это поле устраивало.
> 
> Насколько я понимаю, поле "Комментарий" имеется не только на странице ОТК, но и на других страницах тоже. И я подозреваю, что стили у всех этих полей сделаны одинаково. Таким образом, это не проблема только одной конкретной страницы. ОТК просто первой мне попалась мне на глаза, поэтому я и указал ее в тикете.

Ага. Я писал исходя из заголовка и описания тикета. Там недвусмысленно указан интерфейс ОТК. Остальные интерфейсы я тоже посмотрел и там с полем комментарии тоже все хорошо (кроме случая с инернет эксплорером).
> 
> > Не, ну если вы тут из спортивного интереса дискутируете и для поиска истины, то ничего не имею против продолжения.
> 
> Не знаю, как другие, а я пишу сюда не из спортивного интереса, а делаю конкретное предложение по улучшению продукта. Если ты имеешь что-то против установки полям ввода fallback-значения ширины 100% - не стесняйся, высказывай свои аргументы.

Против ничего не имею, если это сделает жизнь других пользователей БД комфортнее, то почему бы и да))

Позволь поинтересоваться, какой браузер так отображает комментарное поле?

**Comment by alx4** [comment]
> > Таким образом, это не проблема только одной конкретной страницы. ОТК просто первой мне попалась мне на глаза, поэтому я и указал ее в тикете.

Тут я оказался неправ. Вчера вечером поленился проверить. В других местах стили, действительно, такие же, но верстка сделана по-другому. Видимо, поэтому ширина auto не приводит к таким неудобствам, как на странице ОТК.

Проблема еще в том, что я не знаю, как посмотреть данные на многих страницах. Например на странице "Ремонт" у меня открывается форма ввода серийного номера и кнопка "Далее", нажимать которую я боюсь, так как не знаю, что запишется в БД при ее нажатии (боюсь что-нибудь испортить). Есть где-то мануал для этой нашей системы?

> Позволь поинтересоваться, какой браузер так отображает комментарное поле?

Скриншоты сделаны firefox'ом. Теперь благодаря добавлению `width: -moz-available` firefox отображает нормально, но все остальные браузеры (кроме firefox и chrome) будут по-прежнему отображать так же, так для них ширина не задана.

**Comment by ADC-Andrei** [comment]
> > > Таким образом, это не проблема только одной конкретной страницы. ОТК просто первой мне попалась мне на глаза, поэтому я и указал ее в тикете.
> 
> Тут я оказался неправ. Вчера вечером поленился проверить. В других местах стили, действительно, такие же, но верстка сделана по-другому. Видимо, поэтому ширина auto не приводит к таким неудобствам, как на странице ОТК.
> 
> Проблема еще в том, что я не знаю, как посмотреть данные на некоторых страницах. Например на странице "Ремонт" у меня открывается форма ввода серийного номера и кнопка "Далее", нажимать которую я боюсь, так как не знаю, что запишется в БД при ее нажатии (боюсь что-нибудь испортить). 

Кнопку "Далее" можно нажимать. Запись в БД происходит при нажатии "Сохранить данные" в нижней части интерфейсов. Иногда доступна только после введения серийника и нажатия "Далее".


>Есть где-то мануал для этой нашей системы?
> 
Насколько я знаю, пока нет. Надо написать краткую инструкцию, тут полностью согласен.

> > Позволь поинтересоваться, какой браузер так отображает комментарное поле?
> 
> Скриншоты сделаны firefox'ом. Теперь благодаря добавлению `width: -moz-available` firefox отображает нормально, но все остальные браузеры (кроме firefox и chrome) будут по-прежнему отображать так же, так для них ширина не задана.

Проверил в Хроме, Вивальди, Мозиле, Эдж - все ОК.

**Comment by adc-san** [comment]
> В других местах стили, действительно, такие же, но верстка сделана по-другому. Видимо, поэтому ширина auto не приводит к таким неудобствам, как на странице ОТК.
Может быть имеет смысл изменить вёрстку, раз в других местах нет неудобств?

Я согласен с предложением Алексея. Думаю, что такое решение будет вполне приемлемым и работать во всех браузерах:
```
width: 100%;
width: -moz-available;
width: -webkit-fill-available;
```

**Comment by adc-san** [comment]
И вообще я думаю,что можно обойтись стандартными средствами без всяких -moz или -webkit
