### ISSUE TITLE
Заголовки столбцов таблицы смещены относительно контента

### ISSUE THREAD

**Issue by alx4** [Neolined/DatabaseADC#91]
В таблице изделий на главной странице нет вертикальных границ ячеек. Поэтому визуально разделение таблицы на столбцы происходит по select'ам в заголовке ("№", "Тип", "Имя" и т.д.). Однако сами эти select'ы не занимают всю ширину ячеек, а смещены влево. Таким образом, хотя select'ы и находятся в тех же столбцах, что и контент таблицы, визуально создается впечатление, что контент смещен относительно заголовка таблицы (выходит за пределы соответствующего столбца):

![ss1](https://user-images.githubusercontent.com/84128875/121466243-89f75380-c9d0-11eb-9106-86d0f0c0e67b.jpg)

Предлагаю устранить это недоразумение каким-либо способом. Как возможные варианты могу предложить:
1. добавить в таблицу вертикальные линии, разделяющие столбцы;
2. сделать так, чтобы select'ы занимали всю ширину содержащих их ячеек таблицы;
3. выравнивать select'ы в ячейке вправо, а не влево.

**Comment by Neolined** [comment]
Улучшено: 40cf033bc8debbb6bcf5e5260d5f2771a5a41339
В таблицу добавлены вертикальные линии, разделяющие столбцы. Изменены кнопки для переходы в историю.

@alx4
@ADC-Andrei
@alx4

**Comment by ADC-Andrei** [comment]
Линии есть, визуально все норм, ИМХО. Закрываю тикет.
