### ISSUE TITLE
Добавить в историю колонку Местоположение

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#93]
Иначе по истории не понятно откуда куда ходило изделие по фирме

**Comment by adc-san** [comment]
В интерфейсах приёмка и возврат записывать location в историю

**Comment by Neolined** [comment]
Предложение от Андрея. В столбцы `whom_order` (От кого принята) и `order_from` (Кому отправлена) записывать внутренние перемещения в компании, т.е. брать текущее местоположение из `products` и записывать в вышеуказанные столбцы в таблицу `history`. Но, если данные заносятся через возврат:
1. если изделия с таким серийным номером в базе есть, то данные записывать, не из местоположения в `products`, а из `owner`(владелец) => `whom_order` (От кого принята), и select (выбор ) => `order_from` (Кому отправлена).
2. если изделия с таким серийным номером в базе нет, то поле ввода "от кого" => `whom_order` (От кого принята), select (выбор ) => `order_from` (Кому отправлена).
@adc-san
@ADC-Andrei

**Comment by adc-san** [comment]
> Предложение от Андрея
Я уже устно отвечал на это предложение, продублирую тут.
Считаю нецелесообразным использовать для хранения местоположения не предназначеные для этого столбцы.
Столбцы whom_order и order_from предназначены для записи внешних перемещений и текст в них может быть произвольным, а местоположение платы внутри АДС имеет строго определённый набор вариантов.
Я создал в таблице history поле location, аналогичное тому что в products.
Предлагаю при записи информации в историю из интерфейсов Возврат и Приёмка записывать значение location.

**Comment by ADC-Andrei** [comment]
Зачем различать внутренние и внешние перемещения? Зачем два столбца с одинаковым смыслом?

**Comment by adc-san** [comment]
Смысл location в том что варианты местоположения внутри фирмы строго определены и это важно, т.к. нам нужно фильтровать записи по этому полю. А местоположение снаружи может быть произвольным текстом, в этом вся разница.
Обсуждали устно  и вроде договорились на том;
> при записи информации в историю из интерфейсов Возврат и Приёмка записывать значение location.
