### ISSUE TITLE
Улучшение: на главной подсказать пользователю что включены фильтры

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#95]
Иногда не очевидно, что страница отфильтрована. Предлагаю при наличии активных фильтров подсвечивать кнопку "Показать фильтры" или просто не прятать их.

**Comment by Neolined** [comment]
Улучшено: b978ac7179120f8f56a48fce07b3e447099eeb59
Теперь при наличии активных фильтров подсвечивается кнопка "Показать фильтры"

@adc-san
@ADC-Andrei

**Comment by ADC-Andrei** [comment]
Проверено - кнопка мерцает как неисправная люминисцентная лампа
