### ISSUE TITLE
Улучшение: в интерфейсе ОТК отображать несоответствия и статус проверки.

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#96]
Для контролёра ОТК важно знать есть ли несоответствия на плате, а также прошла ли она проверку.
Предлагаю:
- отобразить в интерфейсе наличие несоответствий(и ссылку на страничку с несоответствиями)
- отобразить в интерфейсе статус проверки
- ссылку на историю платы

**Comment by ADC-Andrei** [comment]
Под проверкой имеется в виду тестирование.

**Comment by Neolined** [comment]
Улучшено: 60cce5397ad8fc2b5291d4c4ebc88c7c3e9877d5
В интерфейсе ОТК теперь отображены несоответствия и статус проверки.

@adc-san
@ADC-Andrei
@alx4

**Comment by ADC-Andrei** [comment]
Проверил - работает
