### ISSUE TITLE
Добавить ссылку на главную страницу базы в логотип АДС

### ISSUE THREAD

**Issue by adc-san** [Neolined/DatabaseADC#97]
Производство просит добавить ссылку на главную страницу базы со всех страниц интерфейсов.
Чтобы быстрее попадать на Главную(которой часто пользуются)
Типа так:
```
<a href="./">
<img id="adc" src="images/adc.png" align="center">
</a>
```

Заодно предлагаю вынести повторяющиеся в разных интерфейсах части хедера, как например логотип, в отдельную функцию, аналогично CreateMenu.

**Comment by Neolined** [comment]
Сделано: d561730d28e6ed9b5f22a00a60fadcf5bf56202d
Вынесены повторяющиеся в разных интерфейсах части хедера в отдельные функции

@adc-san
@ADC-Andrei

**Comment by ADC-Andrei** [comment]
Ссылка на главную в логотипе работает.
Разные части хедера проверить не могу - не знаю о чем речь))
