### ISSUE TITLE
Сортировка UID заказов в интерфейсе ОТК

### ISSUE THREAD

**Issue by ADC-Andrei** [Neolined/DatabaseADC#98]
Мне (а может быть и не только) было бы значительно удобнее, если бы в раскрывающемся списке "UID заказа" свежедобавленные заказы оказывались в поле зрения, а не спрятанными как сейчас.
Иначе приходится каждый раз забивать 7 цифр заказа ручками, не смотря на то, что база этот номер уже знает.

**Comment by adc-san** [comment]
Там нет раскрывающегося списка, это браузер тебе так подсказывает.
Предложение о подсказках уже есть: #61
Пиши туда в какие поля тебе нужны подсказки
